### ISSUE TITLE
font-lock-ensure is too new

### ISSUE THREAD

**Issue by alezost** [jaor/geiser#105]
`font-lock-ensure` (used in commit 2c8e3e042ef8da63550fec3982b462773acafe17) is from the future.  The latest Emacs release (24.5.1) does not have it.

**Comment by dleslie** [comment]
parenface does it this way:

https://github.com/tarsius/paren-face/commit/95f38d871f0162567d985cc3bac055fa86615475

**Comment by jaor** [comment]
oh, my bad: org-mode provides a definition in its compatibility mode and it tricked me! i've pushed a fix and will release 0.8.1 shortly
