### ISSUE TITLE
problem in orgmode babel

### ISSUE THREAD

**Issue by autosquid** [jaor/geiser#107]
This is my config:

```
(setq geiser-default-implementation 'guile)


(org-babel-do-load-languages
'org-babel-load-languages
'((scheme . t)
 (emacs-lisp . t)
 (ruby . t)
 (R . t)
 (python . t)
 (C . t)
 (sh . t)))
```

Here is a test source code block in orgmode:

```
#+begin_src scheme :results output
(write "hello world")
(+ 2 2)
#+end_src
```

When I press `C-c C-c` to execute the code block, a new window opens and become selected.

**Comment by jaor** [comment]
@autosquid what version of org-mode are you using?

**Comment by autosquid** [comment]
@jaor  I'm with org-mode 8.3.2

**Comment by autosquid** [comment]
@jaor  Here is someone reporting the same problem: http://emacs.stackexchange.com/questions/17240/org-babel-evaluation-of-code-block-always-creates-new-window

**Comment by jaor** [comment]
@uuplusu, thanks for the pointer. i'll try to take a look during the weekend!

**Comment by jaor** [comment]
@autosquid, sorry for the long delay: i've finally got a bit of time to try and reproduce this problem in my system.  i don't know enough about babel's internal to locate the cause, but a simple cure seems to be to wrap the body of org-babel-scheme-execute-with-geiser (in org's ob-scheme.el) with `save-excursion`... that is, make it start as:

```elisp
   (save-window-excursion
      (with-temp-buffer
        (insert (format ";; -*- geiser-scheme-implementation: %s -*-" impl))
        (newline)
        (insert (if output
```

some of the buffer manipulations there (possibly combined with the ones induced by geiser) is causing the window dance, but i cannot quite tell whose the culprit.  perhaps ob-scheme's author(s) would know?

**Comment by xuchunyang** [comment]
> some of the buffer manipulations there (possibly combined with the ones induced by geiser) is causing the window dance, but i cannot quite tell whose the culprit. perhaps ob-scheme's author(s) would know?

`ob-scheme` calls `run-geiser` (which eventually calls `switch-to-buffer` or `switch-to-buffer-other-window`).

**Comment by jaor** [comment]
On Wed, Nov 08 2017, Chunyang Xu wrote:

>     some of the buffer manipulations there (possibly combined with the
>     ones induced by geiser) is causing the window dance, but i cannot
>     quite tell whose the culprit. perhaps ob-scheme's author(s) would
>     know?
>    
> ob-scheme calls run-geiser (which eventually calls switch-to-buffer or
> switch-to-buffer-other-window).

the behaviour of the repl window is configurable in geiser using
variables such as geiser-repl-use-other-window and
geiser-repl-use-other-window.  it is the caller of run-geiser who has to
set those parameters the way it fits their needs...

**Comment by jaor** [comment]
sorry, i meant geiser-repl-use-other-window and *geiser-repl-window-allow-split*!

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/107
