### ISSUE TITLE
geiser-connect broken with guile

### ISSUE THREAD

**Issue by byulparan** [jaor/geiser#110]
I use Emacs 24.5.2, geiser-20151020.1729(from melpa), guile-2.0.11 on OSX.
in Terminal, I start "guile --listen", then geiser-connect but.
I get next message repeatly in emacs....

    ERROR: In procedure fport_fill_input: Resource temporarily unavailable
    scheme@(guile-user)> While reading expression:

is it bug(emacs,geiser,guile...) or my setup problem? 
Thank you.

**Comment by jaor** [comment]
i have the same versions of emacs, guile and geiser and, on a debian
box, cannot reproduce the problem, so it's most probably something
OSX-specific... any mac user around?

**Comment by byulparan** [comment]
hmm...I was test on ubuntu, it works fine. maybe It's not geiser's problem. Thank you.

**Comment by rprimus** [comment]
Tue Nov 24 14:33:33 GMT 2015

OSX:
```
ProductName:	Mac OS X
ProductVersion:	10.11.2
BuildVersion:	15C47a
```

I get the same.  (Just posting here for completeness.)

Here are the errors from the terminal session (running ```guile --connect```:

```
Enter `,help' for help.
scheme@(guile-user)> Backtrace:
In ice-9/boot-9.scm:
 157: 13 [catch #t #<catch-closure 10dc08f40> ...]
In unknown file:
   ?: 12 [apply-smob/1 #<catch-closure 10dc08f40>]
In ice-9/boot-9.scm:
 157: 11 [catch #t #<procedure 10df31e70 at system/repl/server.scm:140:10 ()> ...]
In unknown file:
   ?: 10 [with-continuation-barrier #<procedure 10dc0a6e0 at system/repl/server.scm:158:3 ()>]
In ice-9/boot-9.scm:
 157: 9 [catch #t #<catch-closure 10dc0a6c0> ...]
In unknown file:
   ?: 8 [apply-smob/1 #<catch-closure 10dc0a6c0>]
In system/repl/server.scm:
 164: 7 [#<procedure 10dc0a6e0 at system/repl/server.scm:158:3 ()>]
In system/repl/repl.scm:
 142: 6 [start-repl* scheme #f #<procedure prompting-meta-read (repl)>]
 168: 5 [run-repl* # #<procedure prompting-meta-read (repl)>]
 123: 4 [#<procedure 10d7e4740 at system/repl/repl.scm:118:4 (key . args)> system-error ...]
In ice-9/format.scm:
1593: 3 [format #<input-output: socket 16> "While reading expression:\n"]
 766: 2 [format:format-work "While reading expression:\n" ()]
  81: 1 [anychar-dispatch]
In unknown file:
   ?: 0 [write-char #\space #<input-output: socket 16>]

ERROR: In procedure write-char:
ERROR: In procedure fport_write: Resource temporarily unavailable
Backtrace:
In ice-9/boot-9.scm:
 157: 2 [catch #t #<catch-closure 10dc08f40> ...]
In unknown file:
   ?: 1 [apply-smob/1 #<catch-closure 10dc08f40>]
In ice-9/boot-9.scm:
 157: 0 [catch #t #<procedure 10df31e70 at system/repl/server.scm:140:10 ()> ...]

ice-9/boot-9.scm:157:17: In procedure catch:
ice-9/boot-9.scm:157:17: In procedure fport_write: Resource temporarily unavailable
```

**Comment by byulparan** [comment]
without geiser get same error message...
I run two guile  
first guile(server)

     (use-modules (system repl server))
     (spawn-server (make-tcp-server-socket))
second guile(client)

     (define client (socket PF_INET SOCK_STREAM 0))
     (connect client AF_INET (inet-aton "127.0.0.1") 37146)

so..I think it guile's bug....so I report to bug-guile@gnu.org  yesterday.

**Comment by rprimus** [comment]
Tue Nov 24 14:44:20 GMT 2015

Telnet'g to localhost:37146 connects and produces the guile prompt, however, the same continuous stream of the following:

```
cheme@(guile-user)> While reading expression:
ERROR: In procedure fport_fill_input: Resource temporarily unavailable
scheme@(guile-user)> While reading expression:
ERROR: In procedure fport_fill_input: Resource temporarily unavailable
scheme@(guile-user)> While reading expression:
ERROR: In procedure fport_fill_input: Resource temporarily unavailable
```
This time, there were no errors/backtraces shown in the original server (```guile --listen```) session.

**Comment by rprimus** [comment]
Tue Nov 24 14:49:51 GMT 2015

Cool!
