### ISSUE TITLE
racket mode got  stacked

### ISSUE THREAD

**Issue by vimniky** [jaor/geiser#111]
I have some problem with racket mode .  when I enter racket mode  , emacs just got blocked . I can't figure out why . Anyone  can help ?

**Comment by dleslie** [comment]
Can you tell us:

* What OS you're using
* Which version of Racket is installed
* How Geiser is installed and configured

**Comment by dleslie** [comment]
Hello, @vimniky ?

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/111
