### ISSUE TITLE
version check on repl startup breaks when binary contains spaces

### ISSUE THREAD

**Issue by ilohmar** [jaor/geiser#117]
Tested with racket 6.1 on windows 7, NTEmacs using the cygwin bash, and current melpa geiser.

Quick fix: `(shell-quote-argument binary)` instead of plain `binary` in `geiser-racket--version` (and similarly for other implementations, I suppose).

Better fix: Do not use the shell at all, it is prone to quoting issues, let alone the configuration maze on windows.  This should work much more robustly using `call-process` wrapped in `with-temp-buffer`.

Sorry for the armchair feedback w/o pull request, it's lunch break here :)

**Comment by jaor** [comment]
@ilohmar, thanks for the report, and sorry for the late reply.  `shell-quote-argument-binary` is so simple a solution that i'm wondering what concrete issues do you have in mind to prefer the more complex solution?

**Comment by ilohmar** [comment]
In this concrete case, I do not have any further issues in mind, and with a little distance I think you're probably right.

My comment *is* based on previous experience, however.  I have fought quoting issues in `magit` for several months, and it's always worst on windows, where there are different versions of emacs, the shell, wrong line endings, different path separators etc.  So nowadays, I try to avoid shell commands entirely (inside emacs functions, of course) when it's not absolutely necessary.

**Comment by jaor** [comment]
okay, i've been lazy and used shell-quote-argument in my last commit to master... if that gives no immediate problems, let's call it a fix and close the issue, please.

**Comment by ilohmar** [comment]
Can only test the windows case after my christmas break, but I'll close it for now as I already checked that this works :)  Thanks!
