### ISSUE TITLE
C-x C-e does not work with guile

### ISSUE THREAD

**Issue by turbopape** [jaor/geiser#119]
I am able to compile the buffer , but evaluating a sexp behind point causes guile to enter debug mode with a no such language error.

I am on emacs 25.0.5 guile 2.1.1 and latest geiser from Melpa. 

Here is the exact error message:
ERROR: In procedure scm-error:
ERROR: no such language objcode

           0 (scm-error misc-error #f "~A ~S" ("no such language" objcode) #f)

**Comment by turbopape** [comment]
I meant Melpa of course.

**Comment by turbopape** [comment]
I saw this was already reported in #112

**Comment by davexunit** [comment]
This is a duplicate of #112

**Comment by turbopape** [comment]
Yep.
