### ISSUE TITLE
Invalid function: geiser-doc--with-buffer

### ISSUE THREAD

**Issue by fedeinthemix** [jaor/geiser#121]
I'm using Geiser 0.8.1 together with Guile 2.0.11 and Emacs 24.5.1. If I press "C-c C-d d" (bound to 'geiser-doc-symbol-at-point') the minibuffer gives the error: "Invalid function: geiser-doc--with-buffer" and the file that I'm editing is overwritten with the documentation!

**Comment by jaor** [comment]
how have you installed geiser? what's your configuration for geiser,  if
any?

**Comment by fedeinthemix** [comment]
I have installed it with the functional package manager Guix
http://www.gnu.org/software/guix/. The only thing that happens at startup
is that 'geiser-autoloads.el' is loaded (as in emacs packages). The file
looks like this:

(require 'geiser)
(setq geiser-scheme-dir
"/gnu/store/fxkhjh0vc0s5pbqqvk89sj2grrdcpj6v-geiser-0.8.1/share/geiser")
(provide 'geiser-install)

I also checked that I get the same behavior by starting Emacs with "-Q" and
adding the right directory to 'load-path' and loading geiser with '(require
'geiser-install)'.

Regards,
Fede

**Comment by alezost** [comment]
Hello, Jao and Federico!

I think I know what happens.  To reproduce it (with the current master),
you need to 'make' the repo (it's important, as it happens only if you
have `geiser-doc.elc` file).

So, start geiser REPL (I used "M-x run-guile" but it should probably
work with other implementations as well) and open any scheme file.  Now
run `geiser-doc-symbol-at-point` command (`C-c C-d d`), and you'll get
the described error.

So, IIUC this happens because (geiser-popup--define ...) line is placed
in the bottom of `geiser-doc.el`.  It defines `geiser-doc--with-buffer`
macro too late: `geiser-doc-symbol` function uses this macro, but at the
compilation time it does not exists, so instead of expanding,
`geiser-doc--with-buffer` is used as a function.

This issue can be solved if (geiser-popup--define doc ...) line will be
moved to the beggining of `geiser-doc.el` file.

The same thing may happen with other files that have
`geiser-popup--define` in the bottom (I didn't look at these files
though, perhaps the code above does not use `geiser-XXX--with-buffer`).

**Comment by fedeinthemix** [comment]
Hi Alex,

I think you are right as I get the correct behavior if I press C-M-x (bound to 'eval-defun'; with or without prefix) on top of 'geiser-doc-symbol' in the 'geiser-doc.el' file.

I also get the correct behavior if I load 'geiser-doc.el', but it manifests the problem if I load 'geiser-doc.elc'.

**Comment by jaor** [comment]
if geiser is compiled but not installed, the way to load it is by means
of 

      (load "<path-to-build-directory>/elisp/geiser-load")

(see http://geiser.nongnu.org/geiser_2.html#From-the-source_0027s-mouth)

does that load procedure also reproduce the problem?

**Comment by alezost** [comment]
It doesn't matter if geiser installed or not, and how it is loaded.
The only important thing: it should be compiled.

Here is the full recipe:

1. 'make' the repo

2. emacs -Q

3. Evaluate (load ".../geiser/elisp/geiser.el")

4. M-x run-guile

5. Switch to a scheme buffer:

  - C-x b new-buffer
  - M-x scheme-mode  (implementation 'guile')

6. Write "list" there.

7. Press "C-c C-d d" on the "list" and you'll get the described error.

**Comment by jaor** [comment]
That problem is that the way of loading a compiled geiser in step 3. is
not correct.  As documented, you should load geiser-load.elc instead of
geiser.el: the problem is trying to load a compiled geiser using
geiser.el.

If i follow your steps, but in 3 use:

     (load "<build-directory>/elisp/geiser-load")

things work fine for me.  Do they work for you that way?

**Comment by alezost** [comment]
Nope, it is absolutely not relative if it's `geiser`, `geiser-load`,
`geiser-load.elc` or whatever.  The issue persists anyway.

@jaor, did you try to reproduce it after running 'make'?  I think
compiling the files manually in emacs will be "impure", as
`geiser-doc--with-buffer` macro may already exist in the compilation
time.  After `make`, I have the following thing in the compiled
`geiser-doc.elc` file:

```elisp
(defalias 'geiser-doc-symbol #[(symbol &optional module impl) "SOME-BINARY-STRING-HERE"  [impl geiser-impl--implementation module symbol ds geiser-doc--module geiser-eval--get-module geiser-doc--get-docstring message "No documentation available for '%s'" geiser-doc--with-buffer geiser-doc--render-docstring geiser-doc--pop-to-buffer] 7])
```

As you can see, there is `geiser-doc--with-buffer` symbol there, which is
the root of the issue.  As I wrote before, if the line:

    (geiser-popup--define doc "*Geiser documentation*" geiser-doc-mode)

will be moved from the bottom to the top of `geiser-doc.el`, this
problem will be solved, as `geiser-doc--with-buffer` will be expanded
properly.

**Comment by fedeinthemix** [comment]
Hi Jaor,

we basically do install geiser with 

./configure
make
sudo make install

In my (Guix) installation I do not see a file called 'geiser-load*'. Among the various files there is 'geiser-install.el[c]'. Looking at the content of 'geser-load.el.in' from the .tar file I see that the difference of this file compared to 'geiser-install.el' is that it adds the geiser path to the emacs 'load-path'.

In Emacs I inspected the 'load-path' and it includes the path to the geiser files. I then checked that 'geiser-elisp-dir' is defined and points to the geiser directory and that 'geiser-scheme-dir' also points to the right place.

Given that these variables are set correctly, I believe that 'geiser-load' and 'geiser-install' should  have the same effect.

The 'geiser-autoloads.el' file that I mentioned in my first post is a symlink that we are adding to 'geiser-install-el' (similarly for .elc).

Are you using Emacs 24.5.1? We have a geiser package since a long time and I do remember that I did try the documentation functionality and it was working fine. Now, after we upgraded geiser and emacs I've found this problem. Could be a change in the Emacs behavior?

P.S.: The full build log of our package is visible here:
http://hydra.gnu.org/build/859553/log/raw

**Comment by jaor** [comment]
yes, ive tried and works fine for me.  the only difference is that i build
off-tree, so there's only elcs in my elisp directory.  im using configure
/make and a fresh emacs -Q.

**Comment by jaor** [comment]
federico, if you make install, geiser must be loaded with (require
'geiser-install)... is that what you're also doing? without creating
additional symlinks? (it's not i don't want to change the order of
definitions, just trying to understand why things work for me!  :))

alex, afk right now... i'll experiment more later!

**Comment by fedeinthemix** [comment]
yes, that's what I do.

**Comment by alezost** [comment]
Arrr, it doesn't relate to the Guix "geiser" package.  I reproduce it
using geiser from the git repo.

@jaor, please look at the `geiser-doc.elc` file and check if
`geiser-doc-symbol` clause contains `geiser-doc--with-buffer` as
I described above.

**Comment by jaor** [comment]
this is the contents of my geiser-doc.elc:

     (defalias 'geiser-doc-symbol #[(symbol &optional module impl) <binary-string> [impl geiser-impl--implementation module symbol ds geiser-doc--module geiser-eval--get-module geiser-doc--get-docstring message "No documentation available for '%s'" geiser-doc--with-buffer geiser-doc--render-docstring geiser-doc--pop-to-buffer] 7])


and my version of emacs is 24.5.1

**Comment by jaor** [comment]
alex, as you see in the previous message, my geiser-doc-symbol alias is
identical to yours (with the possible exception of the binary string,
which probably is also the same)... so there must be some other
difference: have you tried to build off-tree?

**Comment by alezost** [comment]
wow, cool, it's indeed the same, and I also use emacs 24.5.1, but
I have this issue.  I don't understand how it can work for you as
`geiser-doc--with-buffer` is clearly not expanded as it should.

What is "off-tree"?  Do you mean "geiser from the git repo"?  If so,
then yes, that's what I tried.

Also I have just tried again on another system (previously it
was "GuixSD x86_64", now it is "Arch Linux i686"): I have cloned
the repo, executed `./autogen.sh`, `./configure` and `make` on
it, and repeated the recipe with ``(load ".../elisp/geiser-load")``.
And the issue persists.

**Comment by jaor** [comment]
off-tree means building in a separate directory, not the root of the
checkout... e.g.:

       ./autogen.sh
       mkdir build
       cd build
       ../configure
       make

that creates the elisp directory with the .elc's in build/elisp, instead
of in elisp.

**Comment by alezost** [comment]
Oh, got it, thanks for explaining.  I've tried with configuring
from a "build" directory as you pointed and used
``(load ".../build/elisp/geiser-load")`` but it is still the
same.  Are you sure you didn't get this error?  The documentation
is displayed (in the wrong buffer) and there is an error in the
minibuffer about `geiser-doc--with-buffer`.  Could you try again
please :-)

**Comment by jaor** [comment]
ah! i get the error now, sorry!! the slight problem with moving the call
to geiser-popup--define to the beginning of the buffer is that it uses
an (at that point) undefined function, but it's not something i cannot
live with...

**Comment by jaor** [comment]
okay, i've moved around the code in geiser-doc so that geiser-doc--with-buffer is not used before its definition by geiser-popup-define.  it's not exactly at the top of the file, but it's solving the issue for me (i hope this time for real!).  please guys, let me know whether it's working for you too.

thanks a ton for you help and exquisite patience!!!

**Comment by alezost** [comment]
Great, I confirm the problem is solved now, thank you!

**Comment by fedeinthemix** [comment]
Thanks for your help!

**Comment by cwebber** [comment]
This is a really important fix... I keep clobbering my buffers!  When's the next release coming out? :)

**Comment by alezost** [comment]
I also vote for a release :-)  Especially taking into account another important (for me) fix: https://github.com/jaor/geiser/pull/118

**Comment by jaor** [comment]
yes, a new release is certainly a good idea.  once we fix a couple of things, i'll try to cut a do it . @dleslie thoughts?
