### ISSUE TITLE
chicken 4.10.0 cygwin long start up and no evaluation 20151226

### ISSUE THREAD

**Issue by frankieliu** [jaor/geiser#122]
Hi Jose

-- M-x run-geiser
   takes about a 45 seconds eventually a Chicken REPL buffer will appear

-- I changed to the older geiser-chicken.el in 0814 (keeping everything else the same)
    REPL starts up right away, evaluation did not work of course, because of other
    changes in the code

-- Back on the slow 1226 version, after REPL starts up, geiser-eval-buffer hangs for
   a long time as well, and nothing is sent to the REPL

I don't see any error messages, could you help me to debug what is going on in this new version?
I would be happy to trace it -- if you can give me some starting points on how to do this...

I haven't tried it on linux yet, I was setting up on a cygwin system for a friend, note 0814 version works fine for me on both systems.

Thanks,
-f

**Comment by dleslie** [comment]
I don't think anyone has tried using it with Cygwin. What version of Chicken does Cygwin ship, if any?

Is the Emacs running within Cygwin, as well? It may be that the launch parameters need to be changed. Check if they are correct for Cygwin by:

```(customize-variable 'geiser-chicken-binary)```

The long load time is probably due to it compiling the Geiser library; it should only do that once, unless a bug with using Cygwin causes it to always compiling. You can disable that with:

```(setq geiser-chicken-compile-geiser-p nil)```

There ought to be a ```*geiser dbg*```  buffer hanging around if something went wrong; otherwise, if you do manage to get a REPL up, you can send the following to Chicken in order to have it log everything to ```geiser-log.txt``` in the directory in which the REPL is running:

```(geiser-use-debug-log #t)```

**Comment by frankieliu** [comment]
Hello Dan,

Thanks for helping out.

##### Here are some details:
* Chicken version 4.10.0 rev b259631
* it is one of the available packages
* emacs that I run is also native to cygwin
* emacs version 24.5.1
* The launch parameter is csi which is correct.

##### Starting conditions
* `M-x geiser-restart-repl`
* `M-x run-geiser` 
* both takes a long time to start
* this does not occur with geiser 20150814

##### Testing
* `(setq geiser-chicken-compile-geiser-p nil)`
  * `geiser-restart-repl` is fast, and `geiser-eval-buffer` is fast.
* `(setq geiser-chicken-compile-geiser-p t)`
  * very slow
  * `(geiser-use-debug-log #t)`
    * nothing shows
    * *Geiser debug* doesn't show anything unusual

##### Help

Could you tell me how to debug this problem?
* I don't think the problem is with the geiser library per se?
  * emacs.scm did not change from 20150814
  * there is a emacs.so in the scheme/chicken/geiser/ directory
  * (import geiser) in REPL is fast
  * (load "pathto/emacs.scm") is fast
* Changing geiser-chicken-compile-geiser-p to nil makes a difference
  * but it seems to be only used in geiser-chicken--compile-or-load
  * and as above (load "pathto/emacs.scm") is fast
  * how does this variable affect geiser-eval-buffer?

##### Unrelated

This is probably unrelated, I had to change geiser-chicken because there is no shell-quote-binary or shell-quote-argument with my emacs.  I couldn't find references to these functions.

```lisp
diff geiser-chicken.el geiser-chicken.el~
276,281c276,279
<   (shell-command-to-string (format "%s -e \"(display (chicken-version))\""
<                                    binary)))
<   ;; (shell-command-to-string
<   ;;  (format "%s -e %s"
<   ;;          (shell-quote-binary binary)
<   ;;          (shell-quote-argument "(display (chicken-version))"))))
---
>   (shell-command-to-string
>    (format "%s -e %s"
>            (shell-quote-binary binary)
>            (shell-quote-argument "(display (chicken-version))"))))
```

**Comment by dleslie** [comment]
The compile-or-load only occurs when loading the geiser extensions for CSI; compiling the geiser extensions caused a notable speed increase over running them interpreted. It doesn't effect anything -after- the REPL has first loaded.

It's a bug if it is slow more than once. It shouldn't be recompiling if an emacs.so is present.

Weird, on Windows I don't seem to have shell-command-to-string, shell-quote-binary OR shell-quote-argument.

**Comment by dleslie** [comment]
It's weird that you don't have shell-command-to-string. I'd like to see that fixed; perhaps we should simply detect if it is present and use one or the other?

**Comment by dleslie** [comment]
Do autodoc and completions work?

**Comment by frankieliu** [comment]
Hi Dan,

#### shell-command-to-string
* In my diff, the top file is the modified one
* the modified one still uses shell-command-to-string
* but I commented out the parts that use 
  * shell-quote-binary and 
  * shell-quote-argument

#### existence of emacs.so
* according to the "cond" statement in compile-or-load
  * the force-reload is checked first
  * then the target (emacs.so) is checked second

#### slow down
* There is a slow down on geiser-eval-buffer
* and it doesn't give any results, for example (pp (+ 1 1))
  * with (setq geiser-chicken-compile-geiser-p nil)
    * it is fast and results in a 2 displayed another buffer
  * with (setq geiser-chicken-compile-geiser-p t)
    * it is slow and does _not_ result in 2 or display in another buffer
  * from the above, I find it unusual that eval-buffer is affected by this variable

#### autodoc and completions
* I usually don't use those facilities, could you give me a minimal example

-f

**Comment by jaor** [comment]
ooops! `shell-quote-binary` doesn't exist, and it's actually a typo for
`shell-quote-argument` that i introduced recently.  i've pushed a fix
using the later instead: i think it should exist in all emacs 24 (it
does for sure in emacs 24.5.1 which i'm using).  does the latest master
work better??

**Comment by frankieliu** [comment]
Hello Jose,

The change does not affect the slow down issue:

#### Slow down issue:
1. run-geiser takes 40-50 seconds to complete in 1226 version and about 1 second in 0814 version
2. geiser-eval-buffer doesn't work at all no *geiser dbg* buffer is created
3. Dan's suggestion
    1. `(setq geiser-chicken-compile-geiser-p nil)`
    2. makes all the difference in beginning the REPL, and
    3. it also "corrects" the eval-buffer problem (I don't understand why it does, but it does)
4. can you suggest a way to trace where it is hanging/mis-behaving?
    * I can do that, but I am not familiar enough with the methods to do so in emacs lisp, if you can offer some pointers on how to set break points, stepping, etc that would be great, online I find edebug, but before investing time on that, like to know if that is the most common tool/method for use when debugging emacs lisp, or if there is a better way of doing that.

Thanks,

-f

**Comment by dleslie** [comment]
Does #123 help at all?

**Comment by frankieliu** [comment]
Hi Dan,

I think emacs.scm is fine, since it is unchanged from 0814 which works well.
The hang up I think is in the completion detection.  In which the con :completed
is checked.  I don't know how to look into the hash table for :completed

   #s(hash-table size 65 test eql weakness value rehash-size 1.5 
rehash-threshold 0.8 data ())

But basically it loops indefinitely on the while loop waiting for completion.

-f


I put my notes on the edebug session below.



In my edebug session:

   edebug-defun on geiser-chicken.el geiser--chicken-startup
   Step into geiser-chicken--compile-or-load
   E open eval add (prin1 load-sequence) ; , C-c C-u, C-c C-w
   Step till geiser-eval--send/wait load-sequence
   #+BEGIN_SRC emacs-lisp
     (prin1 load-sequence)
     "(define geiser-stdout (current-output-port))(current-output-port (make-output-port (lambda a #f) (lambda a #f)))(load \"/home/frank/.emacs.d/elpa/geiser-20151230.1442/scheme/chicken/geiser/emacs.so\")(import geiser)(current-output-port geiser-stdout)
     "
     ;------------------------------------------------------------------------------
   #+END_SRC

   Step into (geiser-eval--send/wait load-sequence)
   Step into (geiser-con--send-string/wait)
   E eval

   #+BEGIN_SRC emacs-lisp
     ;------------------------------------------------------------------------------
     (prin1 con)
     (t (:filter . comint-output-filter) (:tq nil #<process Chicken REPL<2>> . #<buffer  tq-temp-Chicken REPL<2>>) (:tq-filter lambda (p s) (geiser-con--tq-filter (quote (nil #<process Chicken REPL<2>> . #<buffer  tq-temp-Chicken REPL<2>>)) s)) (:eot . "\\(
     #[^;]*;[^:0-9]*:?[0-9]+> \\)") (:prompt . "#[^;]*;[^:0-9]*:?[0-9]+> ") (:debug-prompt) (:is-debugging) (:count . 0) (:completed . #s(hash-table size 65 test eql weakness value rehash-size 1.5 rehash-threshold 0.8 data ())))
     ------------------------------------------------------------------------------
     (prin1 str)
     "(define geiser-stdout (current-output-port))(current-output-port (make-output-port (lambda a #f) (lambda a #f)))(load \"/home/frank/.emacs.d/elpa/geiser-20151230.1442/scheme/chicken/geiser/emacs.so\")(import geiser)(current-output-port geiser-stdout)
     "
     ;------------------------------------------------------------------------------
     (prin1 cont)
     geiser-eval--set-sync-retort
     ;------------------------------------------------------------------------------
   #+END_SRC

   Step through until the while statement
   Step into
   (geiser-con--connection-completed-p con id) 

   Here (gethash id (cdr (assoc :completed c)))

   Looking at con:

   #+BEGIN_SRC emacs-lisp
     (prin1 con)
     (t (:filter . comint-output-filter) (:tq ((nil "\\(
     #[^;]*;[^:0-9]*:?[0-9]+> \\)" ((:id . 1) (:string . "(define geiser-stdout (current-output-port))(current-output-port (make-output-port (lambda a #f) (lambda a #f)))(load \"/home/frank/.emacs.d/elpa/geiser-20151230.1442/scheme/chicken/geiser/emacs.so\")(import geiser)(current-output-port geiser-stdout)
     ") (:continuation . geiser-eval--set-sync-retort) (:buffer . #<buffer * Chicken REPL *<3>>) (:connection t (:filter . comint-output-filter) #1 (:tq-filter lambda (p s) (geiser-con--tq-filter (quote (#2 #<process Chicken REPL<2>> . #<buffer  tq-temp-Chicken REPL<2>>)) s)) (:eot . "\\(
     #[^;]*;[^:0-9]*:?[0-9]+> \\)") (:prompt . "#[^;]*;[^:0-9]*:?[0-9]+> ") (:debug-prompt) (:is-debugging) (:count . 1) (:completed . #s(hash-table size 65 test eql weakness value rehash-size 1.5 rehash-threshold 0.8 data ())))) . geiser-con--process-completed-request)) #<process Chicken REPL<2>> . #<buffer  tq-temp-Chicken REPL<2>>) (:tq-filter lambda (p s) (geiser-con--tq-filter (quote (((nil "\\(
     #[^;]*;[^:0-9]*:?[0-9]+> \\)" ((:id . 1) (:string . "(define geiser-stdout (current-output-port))(current-output-port (make-output-port (lambda a #f) (lambda a #f)))(load \"/home/frank/.emacs.d/elpa/geiser-20151230.1442/scheme/chicken/geiser/emacs.so\")(import geiser)(current-output-port geiser-stdout)
     ") (:continuation . geiser-eval--set-sync-retort) (:buffer . #<buffer * Chicken REPL *<3>>) (:connection t (:filter . comint-output-filter) (:tq #5 #<process Chicken REPL<2>> . #<buffer  tq-temp-Chicken REPL<2>>) #1 (:eot . "\\(
     #[^;]*;[^:0-9]*:?[0-9]+> \\)") (:prompt . "#[^;]*;[^:0-9]*:?[0-9]+> ") (:debug-prompt) (:is-debugging) (:count . 1) (:completed . #s(hash-table size 65 test eql weakness value rehash-size 1.5 rehash-threshold 0.8 data ())))) . geiser-con--process-completed-request)) #<process Chicken REPL<2>> . #<buffer  tq-temp-Chicken REPL<2>>)) s)) (:eot . "\\(
     #[^;]*;[^:0-9]*:?[0-9]+> \\)") (:prompt . "#[^;]*;[^:0-9]*:?[0-9]+> ") (:debug-prompt) (:is-debugging) (:count . 1) (:completed . #s(hash-table size 65 test eql weakness value rehash-size 1.5 rehash-threshold 0.8 data ())))
   #+END_SRC
   
   Here (gethash id (cdr (assoc :completed c)))

   It should gethash 1 from

   #s(hash-table size 65 test eql weakness value rehash-size 1.5 rehash-threshold 0.8 data ())

**Comment by frankieliu** [comment]
#### Update:  Error in Linux version as well

Using geiser-20151230.1442 version in linux Ubuntu 15.04
Emacs 24.4.1
Chicken 4.9.0.1
geiser-eval-buffer also does nothing (gets an error geiser-

REPL starts fine (fast), but nothing gets evaluated.

Note (setq geiser-chicken-compile-geiser-p nil) also "solves" the problem.

Note with (setq geiser-chicken-compile-geiser-p t) you get the following error

Error: unbound variable: geiser-eval

which is defined in emacs.scm, so somehow in the new version the geiser
library is not loaded correctly when geiser-chicken-compile-geiser-p is non-nil

**Comment by frankieliu** [comment]
#### Update

1. As mentioned previously, the geiser connection doesn't complete.
2. I traced the call to tq-enqueue
    1. the only difference when geiser-chicken-compile-geiser-p is non-nil vs nil are
        * supression-prefix and suppression-postfix is inserted when using emacs.so
    2. I modified geiser-chicken.el to remove the supression strings

`$ diff geiser-chicken.el geiser-chicken.el~
301,304c301,302
<              ;; (format "%s(load \"%s\")(import geiser)%s\n"
<              ;;         suppression-prefix target suppression-postfix)
<            (format "(load \"%s\")(import geiser)\n" target)
<            )
---
>              (format "%s(load \"%s\")(import geiser)%s\n"
>                      suppression-prefix target suppression-postfix))`

    3. when this is done, tq-enqueue detects a completion, and things run smoothly
    4. it seems that the supression strings are there to temporary disable the
        current-output-port, while loading and importing geiser from emacs.so
        then it is set back to its previous value
    5. removing the suppression strings seems to be a workable solution for now

**Comment by dleslie** [comment]
Perhaps you could make that a pull request? :+1:
