### ISSUE TITLE
Geiser not functioning correctly with Chicken and Org Babel

### ISSUE THREAD

**Issue by gevurah418** [jaor/geiser#125]
Trying to use Chicken Scheme with Org Babel on Windows. I have Geiser set up with Chicken as the default implementation but C-c C-c generates a result block with "an error occurred" every time.

**Comment by jaor** [comment]
afaict, org-babel only supports guile.  i don't know how hard it'd be to
make it more general, but that's a question for org-babel developers and
their bug tracker, i think.

**Comment by gevurah418** [comment]
Oh... Thanks.

**Comment by dleslie** [comment]
#107

**Comment by gevurah418** [comment]
I have that problem too Dan. Thanks.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/125
