### ISSUE TITLE
geiser detects a file as chicken due to the word `use` in `geiser-chicken-builtin-keywords`

### ISSUE THREAD

**Issue by MorganBauer** [jaor/geiser#129]
`geiser-chicken-builtin-keywords` contains `use` which causes any file that contains the word `use`, even in a comment, as a chicken buffer. I suggest that the detection needs to be slightly more complex than a regex over the file.

**Comment by dleslie** [comment]
#130 may be of use to you.

Basically, geiser looks for key words that are related to a scheme in order to attempt to discern the nature of the scheme buffer. This sometimes works, often doesn't; and so I suggest declaring to geiser what scheme you intend to use.
