### ISSUE TITLE
Chicken + OS X: "No Geiser REPL for this buffer"

### ISSUE THREAD

**Issue by opsound** [jaor/geiser#130]
I'm having issues getting Geiser to detect the REPL for my Chicken buffer.

Open `hello.scm`
```
(+ 3 2)
```
`M-x run-chicken`, REPL opens in lower half of frame. In hello.scm, put point after `)`, run `M-x geiser-eval-last-sexp`.
*Chicken REPL*
```
Chicken
(C) 2008-2015, The CHICKEN Team
(c) 2000-2007, Felix L. Winkelmann
Version 4.10.0 (rev b259631)
macosx-unix-clang-x86-64 [ 64bit manyargs dload ptables ]
compiled 2015-08-04 on yves.more-magic.net (Linux)

#;1> 
```
*Messages*
```
Starting Geiser REPL for chicken ... [4 times]
Chicken REPL up and running!
geiser-repl--connection: No Geiser REPL for this buffer (try M-x run-geiser)
```

Chicken was installed with `brew install chicken` on OS X 10.11.3.

Any ideas?

**Comment by opsound** [comment]
Running emacs 24.5.1

**Comment by opsound** [comment]
`geiser             20160215.1732 installed             GNU Emacs and Scheme talk to each other`

**Comment by dleslie** [comment]
This happens because it defaults to Guile if the type of Scheme is ambiguous.

You can reduce the number of implementations defined via customizing the Geiser group; but I prefer to declare the Scheme in use by setting a buffer local variable. As the first line in the file:

```scheme
;; -*- geiser-scheme-implementation: 'chicken -*-
```

**Comment by opsound** [comment]
I see - this did the trick. Thank you.
