### ISSUE TITLE
Add RECEIVE to the supported forms for completion of local bindings

### ISSUE THREAD

**Issue by ecraven** [jaor/geiser#143]
If possible in a simple way, it might be useful to make this extensible for the different Schemes.

**Comment by turbopape** [comment]
Or @ecraven, can you help me showing me the way as how to integrate Kawa?

Envoyé de mon iPhone

**Comment by ecraven** [comment]
see #145.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/143
