### ISSUE TITLE
Geiser chokes on unexpected output

### ISSUE THREAD

**Issue by ecraven** [jaor/geiser#144]
For example, the following guile code will break the REPL (if run non-remotely):

(call-with-new-thread (lambda () (sleep 1) (display "foo\nbar\nbaaz") (newline)))

We should investigate whether we can just keep track of the prompt and put new output _before_ it, not after it.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/26
