### ISSUE TITLE
More keybindings

### ISSUE THREAD

**Issue by ecraven** [jaor/geiser#149]
@jaor, would you mind if we added more (SLIME-like) keybindings?
Things like:
- C-c C-c for compiling/evaluating the current defun
- C-c C-l for loading the current file

**Comment by jaor** [comment]
i'm not opposed to them. we already have a few, like C-c C-k, so a few
more won't hurt.

**Comment by jaor** [comment]
@ecraven C-c C-c is already bound to another function, and C-c C-l loads a file, defaulting to the current one...

**Comment by fice-t** [comment]
@jaor Neither C-c C-c nor C-c C-l are defined for me in Scheme buffers. In the REPL C-c C-c is bound to interrupt (SLIME does this too), but C-c C-l is bound to `comint-dynamic-list-input-ring` for me there.

**Comment by jaor** [comment]
oh.  turns out that running run-scheme loads cmuscheme in my system and
it's that package that defines those shortcuts.

anyway, 368d12c adds C-c C-c to geiser-mode and C-c C-l to geiser-mode
and geiser-repl-mode.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/149
