### ISSUE TITLE
No prints to stdout

### ISSUE THREAD

**Issue by paines** [jaor/geiser#151]
Hi
First of all, thanks for Geiser and the maintanance of it. It is highly appreciated!!! 
I am missing the outputs to stdout like Chickens pp . Mabye I am using geiser wrong, so best is I explain my work procedure, because maybe I am using it not quite correctly:
Fire up emacs:
M-x run-geiser -> chicken
It starts a CSI repl.
I split the window in half for repl and buffer. I load my code to the buffer and press then C-c C-s to activate Geiser evaluation for that bufffer. Then I would normally evaluate the whole region, and interactively change functions / globals and try things for the repl. 
I looked for the output messages from pp in the repl, *Messages* or the  *Geiser dbg* buffer which would popup once things are evalutated, but unfortunatley->no outputs.

**Comment by dleslie** [comment]
Could you maybe post a snippet of example code that breaks?

**Comment by paines** [comment]
Nothing really breaks. I am just missing to see the outputs of print / pp  to stdout when using geiser+chicken. Sorry if my issue is confusing to understand.

**Comment by fice-t** [comment]
@dleslie I can't seem to get the evaluation to work for Chicken (including messages to stdout). For instance:

1. Open a Scheme buffer and choose Chicken
2. `C-c C-z` to open a REPL.
3. In the Scheme buffer type `(+ 1 2)` and eval it with `C-x C-e`.
4. No message will occur.

The above procedure works for Guile.

It seems like nothing is getting evaluated at all. For instance, evaluating `(define f identity)` in the buffer and attempting to evaluate `f` in the REPL gives the error `Error: unbound variable: f`.

Again, the above works in Guile.

**Comment by fice-t** [comment]
@dleslie In the \*Geiser dbg\* I get the following error:
```
Error: unbound variable: geiser-eval

	Call history:

	<syntax>	  (geiser-eval (quote #f) (quote (+ 1 2)))
	<syntax>	  (quote #f)
	<syntax>	  (##core#quote #f)
	<syntax>	  (quote (+ 1 2))
	<syntax>	  (##core#quote (+ 1 2))
	<eval>	  (geiser-eval (quote #f) (quote (+ 1 2)))	<--
#;6> (+ 1 2)
```

**Comment by paines** [comment]
@fice-t 
add (require 'geiser)and (setq geiser-chicken-compile-geiser-p nil)
 to your config and after that, evaluation with chicken+geiser should work like a charm .

**Comment by fice-t** [comment]
@paines Thanks, your solution in #154 helped me with this as well.

**Comment by dleslie** [comment]
@paines Chicken will now fail to run the REPL if the necessary modules are not installed; and will show an error in the Emacs REPL display to that effect.

`apropos` and `chicken-doc` are necessary for providing completions and el-doc support for installed and available eggs, and so cannot be removed without crippling Chicken's Geiser support or making changes to Chicken itself.

I am *not* going to close this issue, however; as it speaks to a larger problem: it should show an error message if the geiser module fails for any reason whatsoever. That message only shows for a subset of issues, at the moment.

**Comment by paines** [comment]
Sounds good. I will test it soon! Thanks for your hard work!
