### ISSUE TITLE
run-guile and run-racket error on Emacs launch

### ISSUE THREAD

**Issue by fice-t** [jaor/geiser#156]
If I use either `run-guile` or `run-racket` (or `run-gracket`) before loading Geiser, then Emacs flashes white (never seen that before), and then I get one of these messages:

`geiser-impl--load-impl: Required feature `geiser-guile' was not provided`
`geiser-impl--load-impl: Required feature `geiser-racket' was not provided`

The REPL then does not load (and refuses to load afterwards). I noticed that it also tries to load my init file for some reason (nothing of use to Geiser is currently in there).

All of the other Geiser `run-` variants work fine.

**Comment by fice-t** [comment]
I tried this with `emacs -Q` and after evaluating `(progn (package-initialize) (run-guile))` it loads my init file as well. The other `run-` commands don't do this.

I forgot to mention that I'm using the latest MELPA installation.

**Comment by fice-t** [comment]
For some reason, after updating I can't reproduce this myself. It definitely wasn't working before.

It seems that `define-geiser-implementation` somehow expanded when `load-file-name` was set to my init file, which doesn't make much sense. Now it seems to be expanding properly.

If it comes up again then I'll re-open this.

**Comment by fice-t** [comment]
Ah, I managed to figure out why I couldn't reproduce last night.

When you install Geiser automatically (as part `package.el` in your init file), it compiles Geiser such that `load-file-name` is set to your init file. This doesn't happen when you download/update it manually after the init process is over.

Perhaps `define-geiser-implementation` should take an explicit file name argument rather than relying on `load-file-name` being a certain value.

**Comment by fice-t** [comment]
@jaor What does the first argument of `geiser-impl--define` really do? I changed it to be always `nil` and it seems to still work.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/156
