### ISSUE TITLE
Cursor position on history cycling

### ISSUE THREAD

**Issue by fice-t** [jaor/geiser#157]
Cycling the history using `M-p` and `M-n` in the REPL currently does not move the cursor. It would be nicer if it behaved like SLIME, where the cursor goes to the end of the input at the end of each command.

**Comment by jaor** [comment]
I think i'd find that behaviour confusing: M-p/M-n are matching the current prefix, so when you issue the command more than once in a row, the cursor will move to the end and you'll lose sight of the prefix you're matching against (that, or the second command matches against a different prefix,, which is even worse).  FWIW, the current behaviour is comint's behaviour too...

**Comment by jaor** [comment]
i guess you want to go to the end of line only when M-p/M-n on empty prefixes?

**Comment by fice-t** [comment]
@jaor 
> so when you issue the command more than once in a row, the cursor will move to the end and you'll lose sight of the prefix you're matching against

Right. That's how SLIME does it. While that part of it can be confusing, I like that I can skip back on a prefix and land at the end.

Perhaps Geiser could highlight the prefix currently being used with Emacs's secondary selection? I'm not sure how that works, but I think it could work. I think I'll submit a feature request over at SLIME for this functionality over there as well.

> i guess you want to go to the end of line only when M-p/M-n on empty prefixes?

If the above or SLIME-like behaviour is unreasonable, then this would still be nice.

**Comment by fice-t** [comment]
@jaor 
Actually, I forgot that SLIME more or less solves the issue by showing the current prefix in the minibuffer so you don't forget. That seems easier to do than secondary selection stuff.

**Comment by jaor** [comment]
ok, let's mark this one as a feature request (thanks @dleslie), i see how it can be useful.  on the other hand, when we implement this, i'd actually like a flag to keep the behaviour as it is now, since i'm used to it and like it better.

**Comment by fice-t** [comment]
I've made a first pass at it. It takes the comint versions and changes them a bit. It seems to work.

```elisp
(defvar geiser-goto-end-when-matching t)
(defun geiser-previous-matching-input-from-input (n)
  "Search backwards through input history for match for current input.
\(Previous history elements are earlier commands.)

This is altered from `comint-previous-matching-input-from-input'.
With prefix argument N, search for Nth previous match.
If N is negative, search forwards for the -Nth following match."
  (interactive "p")
  (let ((opoint (point))
        prefix)
    (unless (memq last-command '(geiser-previous-matching-input-from-input
				 geiser-next-matching-input-from-input))
      ;; Starting a new search
      (setq comint-matching-input-from-input-string
	    (buffer-substring
	     (or (marker-position comint-accum-marker)
		 (process-mark (get-buffer-process (current-buffer))))
	     (point))
	    comint-input-ring-index nil))
    (setq prefix (concat "^" (regexp-quote
                              comint-matching-input-from-input-string)))
    (condition-case e
        (comint-previous-matching-input prefix n)
      (user-error (message "%s" (cadr e)))) ; not found, but pass on the message
    (unless (string= prefix "^") ; not matching anything
      (message "%s; current regexp: %s" (current-message) prefix))
    (unless geiser-goto-end-when-matching
      (goto-char opoint))))

(defun geiser-next-matching-input-from-input (n)
  "Search forwards through input history for match for current input.
\(Following history elements are more recent commands.)

This is copied from `comint-next-matching-input-from-input'.
With prefix argument N, search for Nth following match.
If N is negative, search backwards for the -Nth previous match."
  (interactive "p")
  (geiser-previous-matching-input-from-input (- n)))
```

**Comment by fice-t** [comment]
@jaor Would the above be acceptable behaviour? I haven't had an issue with it so far.

**Comment by jaor** [comment]
yes, i think so... i'll try an adapt your code, making the behaviour
opt-in.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/157
