### ISSUE TITLE
geiser-set-scheme doesn't change font-lock keywords

### ISSUE THREAD

**Issue by fice-t** [jaor/geiser#158]
`geiser-set-scheme` doesn't switch the font-lock keywords.

**Comment by jaor** [comment]
yes, that's not trivial, but would be nice to have.  i'm marking the issue as a feature request, and see what can be done when i find a bit of time.

**Comment by fice-t** [comment]
@jaor I'm not sure what the best way for Geiser to do this is, but using `font-lock-remove-keywords` works for me:

```elisp
(defun geiser-set-scheme ()
  "Associates current buffer with a given Scheme implementation."
  (interactive)
  (geiser-syntax--remove-kws)
  (let ((impl (geiser-impl--read-impl)))
    (geiser-impl--set-buffer-implementation impl)
    (geiser-syntax--add-kws)
    (geiser-repl--set-up-repl impl))
  (when font-lock-mode
    (font-lock-mode -1)
    (font-lock-mode 1)))

(defun geiser-syntax--remove-kws ()
  (unless (bound-and-true-p quack-mode)
    (let ((kw (geiser-syntax--impl-kws geiser-impl--implementation)))
      (when kw
        (font-lock-remove-keywords nil kw)))))
```

**Comment by jaor** [comment]
yes, that works, and it's actually quite convenient for geiser.  i
shamelessly stole your code and pushed a fix for this one: thanks a lot!
(also, i didn't know about bound-and-true-p, thanks for that too)

**Comment by fice-t** [comment]
Thanks, I'm glad you found it useful.

However, your commit appears to miss two things. It doesn't add the keywords of the new scheme implementation `(geiser-syntax--add-kws)`, and it doesn't force a refresh of the font-lock faces.

**Comment by fice-t** [comment]
Oh, I found `(when font-lock-mode font-lock-fontify-buffer)` which is better than just toggling `font-lock-mode`. That seems to refresh font-lock fine.

**Comment by jaor** [comment]
actually, in recent emacsen, font-lock-fontify-buffer is for interactive
use only, and the right way is using either font-lock-ensure or
font-lock-flush.  when they're not available, it's better to call
font-lock-fontify-buffer wrapped with with-no-warnings (i think the 3
argument version was not available either in those versions), as was
done in geiser-syntax--str.

please, check if 94210cd is any better, thanks.

**Comment by fice-t** [comment]
Thanks, I didn't know about those functions (looks like they're new in Emacs 25). Everything seems to change just great now, thanks.

Is there a reason to use both `font-lock-ensure` and `font-lock-flush`? I tried a version just with `font-lock-flush` (in Emacs 25 where it's defined), and that seems to work on its own.

**Comment by jaor** [comment]
ah, i was being lazy: in emacs 24, it's font-lock-ensure that is defined
to do the job and font-lock-ensure is a noop... i'll change that.
thanks again.
