### ISSUE TITLE
Incomplete font-lock in REPLs

### ISSUE THREAD

**Issue by fice-t** [jaor/geiser#159]
Some keywords aren't being font-locked in the REPL buffers.

I believe there's a missing `(font-lock-add-keywords 'geiser-repl-mode (geiser-syntax--keywords))`.

**Comment by jaor** [comment]
it's working for me.  do you have an example of keywords that are not fontified? (fontification is handled in an auxiliary buffer in scheme mode that inherits all the font lock keywords defined for the mode, so there's no font lock keywords for geiser-repl-mode).

**Comment by jaor** [comment]
hmm, i take that back: i've found cases where we don't fontify correctly.  investigating...

**Comment by jaor** [comment]
@fice-t i've pushed a patch that should fix the issue.  please give it a try when you can, thanks!

**Comment by fice-t** [comment]
@jaor That fixes the implementation-specific keywords, thanks.

Though I should have specified which keywords weren't being highlighted. The keywords in `geiser-syntax--builtin-keywords` still aren't being highlighted in the REPL.

**Comment by jaor** [comment]
right.  shared keywords should be highlighted now too.

**Comment by fice-t** [comment]
Yep, thanks.
