### ISSUE TITLE
problems with 'geiser-edit-symbol-at-point'

### ISSUE THREAD

**Issue by fedeinthemix** [jaor/geiser#160]
Hi,

I'm using guile 2.0.11 and a current git checkout and have problems with 'geiser-edit-symbol-at-point'. As an example, it does work in finding 'cut' (a syntax from srfi-26), but can't find 'iota' (from srfi-1), nor definitions in the same file and many other symbols.

**Comment by jaor** [comment]
in guile, iota doesn't belong to srfi-1, but to the internal modules
that have no source code in scheme available.  definitions in the same
file will only be 'jumpable' after you've evaluated them: could it be
you didn't? (e.g., C-c C-k in the buffer, then try again).

**Comment by fedeinthemix** [comment]
I have tried evaluating the same file definitions both with C-c C-k as well
as with C-M-x (on each definition), but I just get the message
"Couldn't find edit location for '<symbol name>'".

**Comment by jaor** [comment]
can you give us an example file exhibiting that behaviour?

**Comment by fedeinthemix** [comment]
As very simple test case, I have the following two procedures in a test.scm
file:

--------------------------------------------------
(define (fbe-1- n)
  (- n 1))

(define (fbe-fact n)
  (if (< n 2)
      1
      (* (fbe-fact (fbe-1- n)) n)))
--------------------------------------------------

If I position the cursor on top of 'fbe-1-' inside of 'fbe-fact', I can't
get Geiser to jump to the definition above.

**Comment by jaor** [comment]
@fedeinthemix i cannot reproduce the problem.  this is what i do:

- open a file foo.scm
- write down code exactly as you quote
- compile the full buffer with C-c C-k

then if i move the cursor around, whenever i'm on `fbe-1-` i see its corresponding autodoc and `M-.` will bring me to its definition.  do you see the autodoc? does evaluating something like `(fbe-fact 3)` work?

**Comment by fedeinthemix** [comment]
I do exactly the same. I do see the autodoc and (fbe-fact 3) does produce
the expected result. It's only M-. that doesn't work.

I also tried disabling every other package with "emacs -Q" and only
executing:

(load-file "~/path-to-geiser/geiser/elisp/geiser.el")
(setq geiser-active-implementations '(guile chez))
(setq geiser-default-implementation 'guile)

with the same result.

Do you have suggestions on how I could provide more information to try to
debug this problem?

**Comment by jaor** [comment]
and your problem is happening with guile, chez or both?

one thing to try is C-u M-x geiser-show-logs, try again, and post here
the contents of the *Geiser messages* buffer...

**Comment by fedeinthemix** [comment]
It happens with both. Here the log:


INFO: REQUEST: <1>: ,use (geiser emacs)
'done

INFO: RETORT: ((error (key . retort-syntax)) (output . "$1 = done
scheme@(guile-user)> "))

INFO: <1>: processed

INFO: REQUEST: <2>: ,geiser-eval (geiser evaluation) ge:set-warnings
((quote medium)) ()

INFO: RETORT: ((result "#<unspecified>") (output . ""))

INFO: <2>: processed

INFO: REQUEST: <366>: ,geiser-load-file "/home/beffa/tmp/test.scm"

INFO: RETORT: ((result "\"#<unspecified>\"") (output . ""))

INFO: <366>: processed

INFO: REQUEST: <367>: ,geiser-eval #f ge:autodoc ('(define)) ()

INFO: <367>: processed

INFO: REQUEST: <368>: ,geiser-eval #f ge:autodoc ('(define)) ()

INFO: <368>: processed

INFO: REQUEST: <369>: ,geiser-eval #f ge:autodoc ('(if define)) ()

INFO: <369>: processed

INFO: REQUEST: <370>: ,geiser-eval #f ge:autodoc ('(if define)) ()

INFO: <370>: processed

INFO: REQUEST: <371>: ,geiser-eval #f ge:autodoc ('(fbe-fact fbe-fact * if
define)) ()

INFO: <371>: processed

INFO: REQUEST: <372>: ,geiser-eval #f ge:autodoc ('(fbe-fact fbe-fact * if
define)) ()

INFO: <372>: processed

INFO: REQUEST: <373>: ,geiser-eval #f ge:autodoc ('(fbe-1- fbe-1- fbe-fact
* if define)) ()

INFO: <373>: processed

INFO: REQUEST: <374>: ,geiser-eval #f ge:autodoc ('(fbe-1- fbe-1- fbe-fact
* if define)) ()

INFO: <374>: processed

INFO: REQUEST: <375>: ,geiser-eval #f ge:autodoc ('(fbe-1- fbe-1- fbe-fact
* if define)) ()

INFO: <375>: processed

INFO: REQUEST: <376>: ,geiser-eval #f ge:symbol-location ((quote fbe-1-)) ()

INFO: RETORT: ((result "((\"file\") (\"line\"))") (output . ""))

INFO: <376>: processed

INFO: REQUEST: <377>: ,geiser-eval #f ge:module-location ((quote (fbe-1-
n))) ()

INFO: RETORT: ((result "((\"file\") (\"line\"))") (output . ""))

INFO: <377>: processed

**Comment by jaor** [comment]
hmmm, there's nothing specially strange in the logs, except for the fact that guile is returning empty locations for those procedures, and then emacs cannot jump there.  but i don't see any errors, which is puzzling.  is autodoc working for `fbe-1-` and the reset? also, you don't have any other version of guile installed in your system, right?

**Comment by fedeinthemix** [comment]
Yes, autodoc is working with fbe-1-, fbe-fact and the other built-ins. I
only have a single guile on my path (2.0.11).

**Comment by jaor** [comment]
i'm really at a loss.  i know chez not always returns locations, so that case is maybe normal, but guile is working just fine for me and others.  is it possible for you to try racket?

**Comment by fice-t** [comment]
@jaor FWIW I can reproduce the issue with the same setup on Guile.

It works for me with Racket though.

**Comment by jaor** [comment]
hmmm.  does it work for you both if you put the code in a module?  e.g.,
if the file is foo.scm, start it with:

    (define-module (foo))

**Comment by jaor** [comment]
so, the long story is that guile cannot reliably provide locations for definitions in files that are not ascribed to a module in a file.  when you evaluate definitions in a file that has no `define-module`, those definitions are made in the module currently active in the repl, and guile-user does not have locations for symbols defined interactively.... there might be some hack to make guile register that, but, at least for now, the rule guile files must have a define-module for module-locations to work.

**Comment by fedeinthemix** [comment]
I can confirm that it does work if I put the definitions in a module.

Thanks for your help looking into this!

**Comment by jaor** [comment]
okay, i'll mark this one as a feature-request for now, since i'm not at
all sure that guile will let me have locations for files not belonging
to a module...

**Comment by jojojames** [comment]
I have a similar problem with guile 2.2.

```
;; ~/foo.scm
(define-module (foo))

(define (test)
  (display "TEST"))

(test)
```

```
;; * Guile REPL *
GNU Guile 2.2.0
Copyright (C) 1995-2017 Free Software Foundation, Inc.

Guile comes with ABSOLUTELY NO WARRANTY; for details type `,show w'.
This program is free software, and you are welcome to redistribute it
under certain conditions; type `,show c' for details.

Enter `,help' for help.
scheme@(guile-user)> ,m (foo)
scheme@(foo)> 
```

```
* Geiser dbg *
=> #<unspecified>

TEST
Expression evaluated was:

(define-module (foo))

(define (test)
  (display "TEST"))

(test)
```

```
* Geiser messages *

INFO: REQUEST: <1>: ,use (geiser emacs)
'done

INFO: RETORT: ((error (key . retort-syntax)) (output . "$1 = done
scheme@(guile-user)> "))

INFO: <1>: processed

INFO: REQUEST: <2>: ,geiser-eval (geiser evaluation) ge:set-warnings ((quote medium)) ()

INFO: RETORT: ((result "#<unspecified>") (output . ""))

INFO: <2>: processed

```
Geiser messages doesn't seem to be populated and edit/goto definition doesn't work.

**Comment by jaor** [comment]
have you tried C-c C-k in the foo.scm buffer first?

**Comment by jojojames** [comment]
Yeah, works that way.

**Comment by jaor** [comment]
that's normal. entering a module in guile doesn't evalute the code you
have in the file automatically: you have to ask for it.  all guile does
is register the namespace.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/160
