### ISSUE TITLE
'geiser-autodoc-mode' intermittently not working with Chez Scheme

### ISSUE THREAD

**Issue by fedeinthemix** [jaor/geiser#161]
Hi,

I'm using a current git checkout of geiser with Chez Scheme 9.4. If find that sometimes the 'geiser-autodoc-mode' does work and sometimes it doesn't: nothing is displayed in the echo area.

**Comment by jaor** [comment]
IIRC, in chez only user-defined procedures have autodoc, right @ecraven?

**Comment by fedeinthemix** [comment]
Just to clarify: this happens with procedures I defined (and compiled) in a
file as well.

**Comment by jaor** [comment]
@fedeinthemix could you please provide an example of a file when that happens?

**Comment by fedeinthemix** [comment]
I probably didn't explain well, sorry. Here is a simple example where it
sometimes happens:

(define (plus a b)
  (+ a b))

(plus 1 2)

When I put the cursor on the second form sometimes it does show the autodoc
and sometimes it does not. The situation seems to change when I restart
emacs. I've not figured out what exactly does influence this, but seems
like a kind of race condition at startup.

**Comment by bmansurov** [comment]
I think for procedures that you created, you need to evaluate them before you can see autodoc. For built-in procedures you need to compile Chez with `generate-inspector-information` set to `#t`.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/161
