### ISSUE TITLE
geiser-eval-last-sexp breaks when including Haskell mode

### ISSUE THREAD

**Issue by kwrooijen** [jaor/geiser#164]
When I include `haskell-mode` as one of my packages it will break Geiser. 

Steps to reproduce:

- Create test.scm file
- Write `(display "test")` in this file
- Save
- execute `M-x run-geiser`
- Choose Scheme implementation (in my case Guile)
- Go to the end of the sexp and run `C-x C-e` (geiser-eval-last-sexp)

Expected to have "test" displayed, instead I get the error message:

````
geiser-syntax--fontify: Wrong number of arguments: #[nil "Â 
\00ÃÄ!	 )" [font-lock-verbose font-lock-fontify-buffer-function font-lock-set-defaults called-interactively-p interactive] 2 2311517 nil], 2
````

This also happens when including `elm-mode`. I can't say for sure but I'm going to assume elm-mode derives from haskell mode (because of syntax similarities), causing it to inherit this error as well.

So yes, very strange. This forces me to remove Elm / Haskell from my package list in order to actually get Geiser to work properly. On a side note: the same error appears when adding `company-elm` to `company-backends`, but not requiring elm-mode itself.

I've written a very simplistic init file that causes the error below.

Tools:
Emacs 24.5.1
Guile 2.0.11
Geiser - Latest from Melpa

````
(require 'package)
(require 'ert)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

(use-package haskell-mode
  :ensure t)

(use-package geiser
  :ensure t)

;; These also cause this error when uncommented

;; (use-package elm-mode
;;   :ensure t)

;; (use-package company
;;   :ensure t
;;   :config
;;   (add-to-list 'company-backends 'company-elm)
;;   (add-hook 'scheme-mode-hook 'company-mode))
````

**Comment by fice-t** [comment]
Looking at the backtrace, it looks like the issue is that haskell-mode and Geiser (as of this week) both redefine `font-lock-ensure` (an Emacs 25 function) to something different.

Here's haskell-mode's definition:
```elisp
(unless (fboundp 'font-lock-ensure)
  (defalias 'font-lock-ensure 'font-lock-fontify-buffer))
```

Geiser's:
```elisp
(when (not (fboundp 'font-lock-ensure))
  (defun font-lock-ensure (&optional beg end)
    (with-no-warnings (font-lock-fontify-region (or beg (point-min))
                                                (or end (point-max))))))
```
It looks like this is the wrong thing to do for both haskell-mode and Geiser, according to the Emacs manual:

> If a package needs to define an alias or a new function for compatibility with some other version of Emacs, name it with the package prefix, not with the raw name with which it occurs in the other version

**Comment by jaor** [comment]
620f0d0 removes the definiton of font-lock-ensure for emacs 24.  let me
know if that fixes the issue for you. thanks both!

**Comment by kwrooijen** [comment]
Just tested, seems to work. thanks!
