### ISSUE TITLE
remote repl interaction (chibi)

### ISSUE THREAD

**Issue by velkyel** [jaor/geiser#165]
I don't understand geiser interaction with remote repl:

$ chibi-scheme examples/repl-server.scm

M-x geiser-connect , Host: localhost, Port: 5556
...geiser correctly open -\* Chibi REPL *- buffer to my server.

After that I open my test.scm file and on C-c C-z geiser create new local repl.  So for example geiser-eval-definition (C-c C-c) use this local repl and not my remote repl.  How can I force geiser to use my remote repl and not open new local?
Probably I misunderstood something important :)

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/165
