### ISSUE TITLE
Add Cyclone support

### ISSUE THREAD

**Issue by dleslie** [jaor/geiser#169]
I have made a feature request to the Cyclone developers to add built-in support for behaviour that is necessary to make Geiser work well.

Cyclone is a new R7RS Scheme that uses Chicken-style Cheney-on-the-MTA for garbage collection, but which supports native threads via an SRFI-18 interface. It performs about as well as Chicken in single-threaded tests.

justinethier/cyclone#96

**Comment by jaor** [comment]
excellent.  thanks!

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/169
