### ISSUE TITLE
Please don't automatically activate in Scheme buffers

### ISSUE THREAD

**Issue by wasamasa** [jaor/geiser#172]
This is somewhat annoying, like if I stroll through an unfamiliar codebase for reading and get autodoc errors every time I slow down a bit.  See also the first point in `(info "(elisp) Coding Conventions")`:

```
 Simply loading a package should not change Emacs’s editing
 behavior.  Include a command or commands to enable and disable the
 feature, or to invoke it.

 This convention is mandatory for any file that includes custom
 definitions.  If fixing such a file to follow this convention
 requires an incompatible change, go ahead and make the incompatible
 change; don’t postpone it.
```

In other words, it would be better to let the user add the necessary activation to `scheme-mode-hook`.

**Comment by alezost** [comment]
Just to mention: it can be easily disabled with
``(setq geiser-mode-auto-p nil)``.

As for me, I would prefer that geiser does not automatically add
`geiser-mode--maybe-activate` to `scheme-mode-hook`.  But I think
such auto-enabling is what most users expect.  And IMO if #173 will be
fixed, this enabling will not be an issue.

**Comment by wasamasa** [comment]
Well, yeah, fixing the linked issue would help greatly.  It's not clear either whether a major mode counts as a change to editing behavior (though it *does* involve custom definitions), however I'd prefer to opt-in than to opt-out.

**Comment by jaor** [comment]
too many people are using geiser right now to oblige them to
re-configure their setups, so i don't thing i'm changing the default.

also, geiser-mode is a minor mode.

**Comment by wasamasa** [comment]
Oh, you're right, it's one.  Still, I'd consider it not always welcome to enable it unconditionally for Scheme buffers.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/172
