### ISSUE TITLE
Make autodoc failure silent

### ISSUE THREAD

**Issue by wasamasa** [jaor/geiser#173]
If I'm in a scheme buffer and put point somewhere, it's not exactly instructive to see a "Autodoc not available (No Geiser REPL for this buffer (try M-x run-geiser))" error all the time.  I'd make this specific failure silent to make more important ones than someone not having a REPL open more prominent.

See also #172.

**Comment by alezost** [comment]
I agree.  This may be really confusing for newbies.
I had a hard time :smile: trying to explain that this error comes from Geiser:
http://lists.gnu.org/archive/html/help-guix/2016-07/msg00080.html

**Comment by jaor** [comment]
20a1a2a should have done do the trick...

**Comment by wasamasa** [comment]
That seems a tad excessive though.  Is that the only error that can originate from autodoc?  If no, I'd either catch only that one or ensure that a REPL is around before trying to use autodoc.

**Comment by jaor** [comment]
i think it's the only significant one.  i've never seen any other error
caught there in years using geiser.  i don't think the logic needed to
implement a tighter net is worth the effort...

**Comment by jaor** [comment]
and there's already an option one can set to auto-start the repl
automatically (`geiser-mode-start-repl-p`), for those that one to ensure
that a REPL is around.

**Comment by jaor** [comment]
(just perused the code again, and it still seems to me that a
non-existing repl is the only reasonable failure mode... i'd keep things
simple, specially given the auto-start flag)

**Comment by wasamasa** [comment]
Hm, now that one's gone and I get the same kind of failures with company-mode instead when typing any text...

**Comment by jaor** [comment]
cc8f043

**Comment by jaor** [comment]
i think the patch above addressed the issue.  please, reopen if needed!
