### ISSUE TITLE
Consider adding eval overlays

### ISSUE THREAD

**Issue by Wilfred** [jaor/geiser#175]
As discussed in http://endlessparentheses.com/eval-result-overlays-in-emacs-lisp.html , it's really nice having the output of evaluating sexps shown inline, rather than in the minibuffer.

**Comment by jaor** [comment]
hmm, really? i've seen that in cider and rather dislike the "feature" (i
turned it off after a couple of days) so i'll need more votes or patches
:)

**Comment by dleslie** [comment]
I vote optional. -Dan

**Comment by alezost** [comment]
I don't like this thing too, but if it can be easily turned
off/on, I don't mind.  My understanding is that such a
feature (optional) will be accepted, it's just: someone who is
interested needs to implement it :-)

**Comment by Wilfred** [comment]
Great! Optional would work well I think.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/175
