### ISSUE TITLE
Completion doesn't work at all

### ISSUE THREAD

**Issue by DemiMarie** [jaor/geiser#177]
On my system, completion doesn't work at all.  I am using Guile.

**Comment by DemiMarie** [comment]
Note that I have disabled automatic connection over TCP sockets by Geiser as this is insecure.

**Comment by alezost** [comment]
What Guile/Geiser version do you use?  Also please give a recipe to
reproduce the bug beginning with:

``emacs -Q -l "<geiser>/elisp/geiser-load"``

**Comment by DemiMarie** [comment]
Problem is that Geiser could not find its Scheme sources.  This is a bug in the `make install` target: it puts the Scheme code in `$PREFIX`, but that is not where the Emacs Lisp code looks for it.

**Comment by jaor** [comment]
how are you loading geiser after make install? are you following the
instructions at the end of http://geiser.nongnu.org/geiser_2.html#From-the-source_0027s-mouth?
that is, are you loading geiser via `(require 'geiser-install)`?

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/177
