### ISSUE TITLE
geiser-doc-symbol-at-point doesn't work with Helm

### ISSUE THREAD

**Issue by raxod502** [jaor/geiser#180]
With `helm-mode` disabled, `geiser-doc-symbol-at-point` works as expected. With `helm-mode` enabled, the list of candidate symbols is displayed correctly, but as soon as I start typing, I get the following error message in the minibuffer (note that I _do_ have a REPL open):

<img width="927" alt="temp" src="https://cloud.githubusercontent.com/assets/6559064/18977713/ab06e70e-8671-11e6-90da-4eab24d3b527.png">

Unfortunately, I do not know how to copy the above text (without using a screenshot), since it's not in the `*Messages*` buffer and it disappears as soon as I press another key.

I would assume that Geiser tries to infer from the current buffer which REPL it should be using, but since Helm creates its own buffer for the completions list, Geiser sees this as the current buffer and reports (correctly) that the current buffer has no REPL. Obviously this isn't desirable behavior, though, since it makes it impossible to use Helm for `geiser-doc-symbol-at-point`.

Similar conflict between Geiser and Helm, but with a different symptom:
- https://github.com/emacs-helm/helm/issues/1030

**Comment by jaor** [comment]
yes, i'm guessing the moment this happens `(current-buffer)` point's to Helm's buffer, not to the scheme buffer it was invoked from.  do you know if helm has any function or variable that could tell us what was the active buffer when it was invoked? (i'm afraid i'm not a helm user and have very limited knowledge of its workings).

**Comment by raxod502** [comment]
Perhaps `helm-current-buffer` would work?

```
helm-current-buffer is a variable defined in `helm-lib.el'.
Its value is #<buffer helm-lib.el>

Documentation:
Current buffer when `helm' is invoked.
```

Here is how I tested it:

```
(global-set-key (kbd "M-\\") nil)
(global-set-key (kbd "M-\\ c")
                '(lambda ()
                   (interactive)
                   (message (buffer-name (current-buffer)))))
(global-set-key (kbd "M-\\ h")
                '(lambda ()
                   (interactive)
                   (message (buffer-name helm-current-buffer))))
```

Then, if I `C-c C-d C-d` in `* Racket REPL *`:

- `M-\ c` echoes `*Minibuf-1*`
- `M-\ h` echoes `* Racket REPL *`

But, it seems like this should be taken care of automatically by Helm, since I see things like `with-helm-current-buffer`. I'm not really sure which library's "fault" the problem is.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/180
