### ISSUE TITLE
Documentation lookup can't find Racket manual

### ISSUE THREAD

**Issue by raxod502** [jaor/geiser#181]
I'm unable to access the manual in Racket documentation lookups (in `geiser-doc-symbol-at-point`). Steps to reproduce:

- `emacs -Q`.
- Load `geiser` somehow; because I'm comfortable with `package.el`, I did the following:
  - `(require 'package)`
  - `(setq package-load-list '((geiser "20160921.910")))`
  - `(package-initialize)`
- `(run-racket)`
- In `* Racket REPL *`, `C-c C-d C-d and RET`.
- In `*Geiser documentation*` for `and`, navigate to `[manual]` and press `RET`.

```
Looking up manual for 'and'... not found
```

I am using:

```
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 on builder10-9.porkrind.org
OS X El Capitan 10.11.6
```

and `geiser` from MELPA (you can see the exact version above).

**Comment by jaor** [comment]
You probably don't have DrRacket configured to show the HTML documentation.  Please, see the discussion in issue #5

**Comment by jaor** [comment]
(one way to check if racket is properly configure is to type `(help and)` in the REPL: that should open a browser with `and`'s documentation: geiser relies on racket's for accessing the help manual).

**Comment by raxod502** [comment]
Interestingly, although I get this error in Geiser:

```
Welcome to Racket v6.6.
racket@> (help and)
help: documentation system unavailable; try http://docs.racket-lang.org/
```

It works properly in the plain `racket` REPL:

```
Welcome to Racket v6.6.
> (help and)
Loading help index...
Sending to web browser...
  file: /Applications/Racket v6.6/doc/reference/if.html
  anchor: (form._((lib._racket/private/letstx-scheme..rkt)._and))
```

Even more bewilderingly, I get a different error in DrRacket:

```
Welcome to DrRacket, version 6.6 [3m].
Language: racket, with debugging; memory limit: 128 MB.
> (help and)
. and: bad syntax in: and
```

Unfortunately, when I try to access Preferences > Browser in DrRacket, it's not obvious to me where I can change the default browser:

<img width="924" alt="20160929204648" src="https://cloud.githubusercontent.com/assets/6559064/18980116/de0a542e-8685-11e6-91fe-4b62d5e252c4.png">

I'll keep investigating; this does not seem like it is solely a Geiser problem, although it is notable that the configuration is correct for the plain `racket` REPL.

**Comment by jaor** [comment]
hmm, looks as if something is not fully working in your racket installation... i'm on linux, and i see this panel in the browser configuration tab:

![racket](https://cloud.githubusercontent.com/assets/80719/18980287/16599540-86d3-11e6-8e10-a44cae7d9c04.png)

and this is what racket tells me at the geiser REPL:

```
Welcome to Racket v6.6.
racket@> (help and)
Sending to web browser...
  file: /usr/share/doc/racket/reference/if.html
  anchor: (form._((lib._racket/private/letstx-scheme..rkt)._and))
racket@>
```

**Comment by raxod502** [comment]
Very odd. I can confirm by running in a virtual machine that what I see is standard for an OS X installation of DrRacket.

**Comment by raxod502** [comment]
Perhaps you only have to set the external browser on Linux, and the system's default browser is used on Mac. This would explain why `help` works correctly, opening Google Chrome, in the plain `racket` REPL. Doesn't explain the other errors, though—they must be separate problems.

**Comment by raxod502** [comment]
As per [the documentation](http://docs.racket-lang.org/reference/Interactive_Help.html?q=help#%28form._%28%28lib._racket%2Fhelp..rkt%29._help%29%29) if I `(require racket/help)`, then `(help and)` works perfectly fine in DrRacket.

It looks like this is indeed a Geiser-specific problem.

**Comment by raxod502** [comment]
I also don't have a `~/.racket` folder, or anything on my filesystem whose name contains `racket-prefs`, as per https://github.com/jaor/geiser/issues/5. I guess this is just a GNU/Linux thing.

**Comment by jaor** [comment]
On Fri, Sep 30 2016, Radon Rosborough wrote:

> As per the documentation if I (require racket/help), then (help and) works perfectly fine in DrRacket.
>
> It looks like this is indeed a Geiser-specific problem.

except that it works for me :) so there's must also be something related
to os x, i guess.  since i cannot reproduce the problem, it's a bit
difficult to debug on my side.

have you tried to require racket/help in geiser's repl too?

**Comment by raxod502** [comment]
OK, I'm not sure what changed, but *now* I get the following in the Geiser REPL:

```
Welcome to Racket v6.6.
racket@> (help and)
Sending to web browser...
  file: /Applications/Racket v6.6/doc/reference/if.html
  anchor: (form._((lib._racket/private/letstx-scheme..rkt)._and))
0:132: execution error: An error of type -10822 has occurred. (-10822)
browser-run: process execute failed: '(#<path:/usr/bin/osascript> "-e" "open location \"file:///Applications/Racket%20v6.6/doc/reference/if.html#(form._((lib._racket%2Fprivate%2Fletstx-scheme..rkt)._and))\"")
```

This happens to be a problem I've encountered before with tmux (see https://github.com/raxod502/radian/issues/120), and if I'm outside tmux, then everything works properly (both `help` and `[manual]`, even without running `(require racket/help)` first).

**Comment by raxod502** [comment]
For the record, the reason that setting a browser is not necessary on OS X is because Racket uses the AppleScript `open location` command when doing a documentation lookup—this delegates to the system's default browser.

I suppose it makes sense that they have OS-specific implementations of this behavior.

**Comment by jaor** [comment]
thanks for the update.  it's a bit of a pity that they don't let you
override the system browser, so that one can read racket's docs using,
say, emacs, without setting it as the default system browser.  i find it
very convenient to browse the manual using emacs-w3m when i'm in geiser.

**Comment by raxod502** [comment]
Yes, I certainly agree. It is rather annoying to have to jump out of Emacs to view documentation—but I have to use Emacs in windowed mode anyways (to get images in the REPL), so it's not a terrible cognitive shift.

The real problem is that when you do the command

```
osascript -e 'open location "file:///Applications/Racket%20v6.6/doc/reference/if.html#(form._((lib._racket%2Fprivate%2Fletstx-scheme..rkt)._and))"'
```

the anchor (`#(form...`) is dropped. So I will have to change this in the Racket source to something like

```
osascript -e 'tell application "Google Chrome" to open location "file:///Applications/Racket%20v6.6/doc/reference/if.html#(form._((lib._racket%2Fprivate%2Fletstx-scheme..rkt)._and))"'
```

But that's a separate issue.
