### ISSUE TITLE
Can't `run-racket` without loading a racket file first

### ISSUE THREAD

**Issue by raxod502** [jaor/geiser#182]
With CIDER, one can `cider-jack-in` without ever loading a Clojure file; everything will be appropriately autoloaded.

However, with Geiser, unless one has opened a Racket file at some point in one's Emacs session, `run-racket` will fail with the error:

```
geiser-impl--load-impl: Required feature `geiser-racket' was not provided
```

I think this is because opening a Racket file loads Scheme mode, or Geiser mode, or something of that sort, which makes the necessary feature available. But it seems like this all should be autoloaded when `run-racket` is invoked.

**Comment by raxod502** [comment]
I don't know why this didn't occur to me earlier, but `run-geiser` works fine. It's just `run-racket`.

**Comment by PythonNut** [comment]
System:
* Arch Linux (latest)
* Emacs 25.1

Procedure:
1. `emacs25.1 -Q`
2. <kbd>M-x</kbd> `package-initialize` <kbd>RET</kbd>
3. <kbd>M-x</kbd> `run-racket` <kbd>RET</kbd>

Seems to be working fine for me.

**Comment by raxod502** [comment]
I just tried to reproduce the issue, and somehow it's started working fine for me! *However*, I still have a VM snapshot that reproduces the problem, so I will try to narrow down what could have changed.

**Comment by fice-t** [comment]
This looks like the same problem as #156.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/182
