### ISSUE TITLE
Incorrect indentation for `shared`

### ISSUE THREAD

**Issue by raxod502** [jaor/geiser#184]
In DrRacket, `shared` is indented like `let`:

```
(shared ([x (list* 1 y)]
         [y (list* 2 x)])
  (cons x y))
```

But in Geiser, there's no special handling for the indentation:

```
(shared ([x (list* 1 y)]
         [y (list* 2 x)])
        (cons x y))
```

Is there a function like CIDER's `define-clojure-indent` that we can use to correct problems like this?

**Comment by jaor** [comment]
yes. see e6535d4, where i've just added proper indentation for `shared`
(specifically for racket).
