### ISSUE TITLE
switch-to-geiser never reconnects a disconnected REPL

### ISSUE THREAD

**Issue by llvilanova** [jaor/geiser#185]
I'm using the geiser REPL through `geiser-connect`. All is great with `geiser-mode-switch-to-repl`until I restart my application (which provides a guile REPL server); then the REPL gets disconnected.

At that point, executing `geiser-mode-switch-to-repl` starts a new guile REPL server, instead of trying to reconnect the one I had.

This is pretty annoying, since I have to kill the new "local" REPL, execute `geiser-connect`, and resume working with that remote REPL. There seems to be no alternative nor tweak to use `geiser-connect` instead of `geiser-run` as a response to `geiser-mode-switch-to-repl` (which ends up calling `switch-to-geiser`, where the decision takes place).

**Comment by jaor** [comment]
yes, i see how this is annoying, and no, there's no workaround other than redefining geiser-mode-switch-to-repl in your emacs.el (probably with an eval-after-load) until we fix the issue :)

**Comment by RenWenshan** [comment]
Is this still relevant, seems working fine here.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/185
