### ISSUE TITLE
REPL syntax highlighting malfunctions when #| appears in an error message

### ISSUE THREAD

**Issue by raxod502** [jaor/geiser#186]
I think this image says it all:

![image](https://cloud.githubusercontent.com/assets/6559064/19224819/85ee5bd6-8e42-11e6-8759-48a8d862d815.png)

After the error message (caused, as it says, by an unbalanced `#|` in my file) is printed in the Geiser REPL, I can no longer get any syntax highlighting because the parser thinks the error message is the start of a block comment.

Perhaps syntax parsing/highlighting should be disabled for error messages, or for part of them?

**Comment by raxod502** [comment]
Similar to #26.

**Comment by jaor** [comment]
selectively disabling syntax highlighting can get a bit tricky and, what can be worse, affect performance: i'll take a look.  i wonder what racket-mode does in a similar situation, maybe we can steal code from there!

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/186
