### ISSUE TITLE
geiser-0.9.tar.gz doesn't include Chez support files

### ISSUE THREAD

**Issue by fedeinthemix** [jaor/geiser#188]
The release file https://github.com/jaor/geiser/releases/download/0.9/geiser-0.9.tar.gz seems to lack the files to support Chez Scheme.

**Comment by jaor** [comment]
oops, just added them to the release tarball, thanks for the heads up!

**Comment by fedeinthemix** [comment]
The files 'geiser-chez.el' and 'geiser-chibi.el' are still missing.

**Comment by jaor** [comment]
added, thanks

**Comment by fedeinthemix** [comment]
I noticed that you closed the 'issue'.  However, I believe that the files
'geiser-chez.el' and 'geiser-chibi.el' are still missing.

**Comment by jaor** [comment]
hmmm? i closed the issue after updating the tarball: when did you check?
i just downloaded it ( https://github.com/jaor/geiser/releases/download/0.9/geiser-0.9.tar.gz)
and i certainly see them there.  you don't?

**Comment by fedeinthemix** [comment]
All is good now.

Thanks!
Fede

P.S.: I wrote you 2 times (once on github and once by email) because I was
unsure if you would get a message from a closed issue.
