### ISSUE TITLE
Emacs, Geiser and Chez Scheme with transcript-on

### ISSUE THREAD

**Issue by haziz** [jaor/geiser#189]
I am working my way through Dybvig's "The Scheme Programming Language" book. I am using Chez Scheme 9.4.1 as my REPL. I am running said REPL within Emacs using Geiser. Chez Scheme has a transcript-on function that records the input and output of the REPL into a text file, which I find useful. By running this however within Emacs and Geiser, I am however getting also a running "commentary" from Geiser that renders the text file output unnecessarily verbose and cumbersome since it includes the very verbose Geiser output. e.g.

> (geiser:eval '#f '(geiser:autodoc '(1 1)))
> ((result "()") (output . ""))
> (geiser:eval '#f '(geiser:autodoc '(2 1)))
> ((result "()") (output . ""))
> (geiser:eval '#f '(geiser:autodoc '(3 1)))
> ((result "()") (output . ""))
> (geiser:eval '#f '(geiser:autodoc '(1)))
> ((result "()") (output . ""))
> (geiser:eval '#f '(geiser:autodoc '(1 1)))
> ((result "()") (output . ""))

How do I restrict the output going to the text file to just the "read" and "print" input and output of the REPL without the unnecessary Geiser "commentary", while still getting the benefits of running it within Emacs and Geiser?

**Comment by jaor** [comment]
@haziz, i'm afraid there's no easy way of avoiding this "running commentary" without substantially changing geiser.  But, this being emacs and the REPL buffer being a text buffer, the transcript function is a bit redundant, no? why not just save the contents of the buffer?

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/189
