### ISSUE TITLE
error opening file with -*- scheme -*- file local comment

### ISSUE THREAD

**Issue by holomorph** [jaor/geiser#191]
I have a file containing the file local `-*- scheme -*-` in the first line of the file.  Interestingly enough the elisp manual is a little weird about this kind of file local variable, as opposed to doing `-*- mode: scheme; foo: bar; ... -*-`.  In any case, opening such a file results in:

```
Debugger entered--Lisp error: (wrong-type-argument listp scheme-mode)
  hack-local-variables-filter(scheme-mode nil)
  hack-local-variables()
  geiser-impl--guess(t)
  geiser-impl--set-buffer-implementation(nil t)
  geiser-mode(1)
  turn-on-geiser-mode()
  geiser-mode--maybe-activate()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook scheme-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook scheme-mode-hook))
  run-mode-hooks(scheme-mode-hook)
  scheme-mode()
  set-auto-mode-0(scheme-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer menurc> "~/.gimp-2.8/menurc" nil nil "~/.gimp-2.8/menurc" (4326451 2055))
  find-file-noselect("~/.gimp-2.8/menurc" nil nil t)
  find-file("~/.gimp-2.8/menurc" t)
  funcall-interactively(find-file "~/.gimp-2.8/menurc" t)
  call-interactively(find-file nil nil)
  command-execute(find-file)
```

**Comment by fice-t** [comment]
That's odd -- it works for me. I used my copy of `~/.gimp.2.8/menurc` and it loads fine.

In your `menurc` what's the value of `(hack-local-variables-filter nil)`? It should be nil.

You can also try to call `edebug-defun` on `hack-local-variables` and see what part of the function is adding `scheme-mode` to its local `result`.

**Comment by holomorph** [comment]
Here, `(hack-local-variables-prop-line nil) => scheme-mode`.

Stepping through, I find myself here
```
                  (and (setq result (hack-local-variables-prop-line
=>                                   handle-mode))
;; Result: scheme-mode
```
Perhaps I've gummed something up somewhere--will look more closely

**Comment by fice-t** [comment]
Any success? Just to make sure, your first line in `menurc` is `; gimp GtkAccelMap rc-file         -*- scheme -*-`, right?

Could you use `edebug-defun` on `hack-local-variables-prop-line` to see where it returns `scheme-mode`? I'm not sure how it could with a nil argument, though.

**Comment by holomorph** [comment]
Correct, that is the first line. Pasting it again:
```
; gimp GtkAccelMap rc-file         -*- scheme -*-
```

Here, which, well, now looking at it makes sense:
```
	      ((looking-at "[ \t]*\\([^ \t\n\r:;]+\\)\\([ \t]*-\\*-\\)")
	       ;; Simple form: "-*- MODENAME -*-".
	       (if (memq handle-mode '(nil t))
=>		   (intern (concat (match-string 1) "-mode"))))
```
and so it returns the symbol `scheme-mode`.

Perhaps this isn't a geiser issue, but an Emacs one. There are some changes in the log of `files.el` that touched hack-local-variables and friends.  I follow emacs master, and perhaps this is the culprit
http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=4a80c8bb276d

**Comment by fice-t** [comment]
Ah, I figured I should have asked for your Emacs version. Alright, it makes sense now.

As a temporary fix, you can add the argument `'no-mode` to the `hack-local-variables` call in `geiser-impl--guess`.

I'd say this is an Emacs bug. When the argument to `hack-local-variables` is nil, then a spec of the form `-*- function -*-` will make `hack-local-variables-prop-line` return `function-mode` which makes `hack-local-variables` error.

For example, create a buffer with this line:

```
# gimp-2.8 GtkAccelMap rc-file         -*- org -*-
```

then do `M-: (hack-local-variables)`. It will error.

Could you submit a bug report upstream?

**Comment by holomorph** [comment]
I agree. Bug#25008 filed. Closing, thanks.
