### ISSUE TITLE
Geiser shadows C-c C-d in Guile REPL

### ISSUE THREAD

**Issue by tger** [jaor/geiser#192]
A QUIT signal is used in the Guile repl to exit from a debugger session. Typing ",q" is another option, but I rather have the standard C-c C-d binding.

Unfortunately C-c C-d is a prefix for all the documentation commands, and the obvious C-c C-d C-d is taken as well (but in the case I probably rather just type ",q"), so I can't really say what would be the best solution here.

**Comment by fice-t** [comment]
>but I rather have the standard C-c C-d binding.

It's just `C-d` according to the manual:

> You can exit a recursive REPL in the same way that you exit any REPL: via ‘(quit)’, ‘,quit’ (abbreviated ‘,q’), or C-d, among other options.

In Geiser you can use `C-c C-q` as an alternative.

**Comment by tger** [comment]
> It's just C-d according to the manual:

Again, shadowed by Emacs.

> In Geiser you can use C-c C-q as an alternative.

Cool, that's what I was looking for.
