### ISSUE TITLE
htdp/sbl support?

### ISSUE THREAD

**Issue by FernandoBasso** [jaor/geiser#193]
I don't even think this is an _issue_ and I am not sure it is related to Geieser itself, still, I would like to ask if it is possible to have a buffer with `#lang` set to something like this:

    #lang htdp/sbl

so that I can use the Basic Student Language (I'm doing a course [here](https://www.edx.org/xseries/how-code-systematic-program-design)) and would rather use Emacs+Geiser rather than DrRacket.

Is this something that Geiser supports (or could support) or I am just seeking a solution in the wrong place?

**Comment by jaor** [comment]
i assume you mean htdp/bsl.  i've just tried to open a file with that
#lang invocation, and C-c C-k seems to work.  also C-u C-c C-z brings me
to the REPL and i can evaluate things there.  so it might work for you.

a hurdle you may encounter is that drracket restarts the REPL every time
you hit RUN, and geiser doesn't by default.  if you want drracket's
behaviour in that regard, you can try using `geiser-restart-repl` and
see how it works for you.

another thing to try is
[racket-mode](https://github.com/greghendershott/racket-mode), which is
designed to follow drracket's philosophy but using emacs.

**Comment by FernandoBasso** [comment]
Yeah, I do mean `htdp/bsl` (not sbl). I tried it again, bu I can't use `check-expect`, for instance. It never returns anything in the REPL.

Thanks for the racket-mode suggestion. I'm taking a look at that too.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/193
