### ISSUE TITLE
cannot load files with C-c C-l

### ISSUE THREAD

**Issue by Rageoholic** [jaor/geiser#194]
There appears to be a bug with canonicalize-path where it fails to expand ~ into /home/user so it can't find anything on ubuntu 16.10.

**Comment by jaor** [comment]
would you please be a bit more specific? what's your configuration and
what do you exactly mean by "it can't find anything"? where's
canonicalize-path defined?

**Comment by Rageoholic** [comment]
So when I try to call geiser-load-file from emacs, somewhere down the stack
(not in any code I wrote) it calls (canonicalize-path "~/sicp/ch1.scm")
which always fails. I'm running the snapshot from MELPA with no other
configuration and it works with Chicken and Racket.

On Friday, November 25, 2016, jao <notifications@github.com> wrote:
>
> would you please be a bit more specific? what's your configuration and
> what do you exactly mean by "it can't find anything"? where's
> canonicalize-path defined?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/dpc0Kcwtap7XClb0Em0xxUyLlvtaX0BG3s2a08PsdyXeypCOVkZldQdB9Mrjqv2n7PClWvZ_bye36mjoVanO78e0YuvH6r-TiSAaCkDuBwGNxZiSWeaoTgTIjcggmgOs8CAvGomHEvxU8vpCXvuxPEIncvy8-g=s0-d-e1-ft#https://github.com/notifications/beacon/AIXP5YchRkbgpQpjXnTleF8yiqSypIjrks5rB0ybgaJpZM4K8INb.gif>

**Comment by jaor** [comment]
On Fri, Nov 25 2016, Rageoholic wrote:

> So when I try to call geiser-load-file from emacs, somewhere down the stack
> (not in any code I wrote) it calls (canonicalize-path "~/sicp/ch1.scm")
> which always fails. I'm running the snapshot from MELPA with no other
> configuration and it works with Chicken and Racket.

canonicalize-path is not called explicitly by geiser, and i cannot even
find it defined in my currently running emacs.  are you having the same
problem starting with emacs -Q and loading geiser by hand?

**Comment by Rageoholic** [comment]
Yes the issue persists with that.
![screenshot from 2016-11-25 21-21-12](https://cloud.githubusercontent.com/assets/8769509/20637724/827f3424-b355-11e6-80cf-19fbc1bf5914.png)

**Comment by jaor** [comment]
oh, i see it's an error in guile.  does the patch i just uploaded solve
the issue for you?

**Comment by Rageoholic** [comment]
No, its saying that functions I *know* I have defined are not defined when I load the file. This is so wierd.

**Comment by jaor** [comment]
@Rageoholic to use geiser safely with guile, it's better to always put your scheme code inside a module, and then enter it (e.g. with C-u C-c C-z).

**Comment by Rageoholic** [comment]
Oh I see. thanks for helping out.
