### ISSUE TITLE
C-c C-k cannot compile source file.

### ISSUE THREAD

**Issue by Athenacle** [jaor/geiser#196]
I updated geiser from MELPA to version 20161126.06, after that C-c -C-k cannot compile a file.
I have tried to minimize the question by starting emacs with "emacs --no-init-file" and then M-x "load-file /path/to/geiser/geiser.el", the problem still existed.

I switched to buffer "Geiser dbg", it said:
```
Compiling /home/wangxiao/test.scm ...

While executing meta-command:
ERROR: Wrong number of arguments to #<procedure 1eb11a0 at /home/wangxiao/.emacs.d/elpa/geiser-20161126.106/scheme/guile/geiser/emacs.scm:44:0 (repl file)>
scheme@(guile-user)> 
```
I opened the source file /scheme/guile/geiser/emacs.scm, at line 44, there is a define-meta-command of geiser-load-file.
How to solve this problem? Thank you.

**Comment by jaor** [comment]
This is a bug i introduced a couple of commits ago.  Could you please
try with my latest patch and see if it solves the problem? (i guess
it'll reach MELPA shortly, if you prefer not to check it out from git).
Thanks!

**Comment by Athenacle** [comment]
I cloned the repository from github and test. Everything works fine. 
Thank you @jaor .
