### ISSUE TITLE
run-geiser gives compile error in Aquamacs

### ISSUE THREAD

**Issue by ashkan-leo** [jaor/geiser#197]
I am using Aquamacs 3.3. When I want to run the REPL, I get the following error:

```
clang: error: no such file or directory: '/Users/user/Library/Preferences/Aquamacs'
;      clang: error: no such file or directory: 'Emacs/Packages/elpa/geiser-20161126.106/scheme/mit/geiser/emacs.c'
;      clang: error: no input files
```

However, the REPL seems to work just fine:

```
2 error> (+ 1 1)

;Value: 2
```

Any idea why I'm getting those errors?

**Comment by ashkan-leo** [comment]
I think the problem is that there is space in the file name.
<img width="562" alt="screen shot 2016-12-10 at 1 53 36 am" src="https://cloud.githubusercontent.com/assets/10341965/21072330/8e752f28-be7b-11e6-9bb0-a8e7f84d2e04.png">

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/197
