### ISSUE TITLE
Debugger opens constantly while editing files

### ISSUE THREAD

**Issue by randre03** [jaor/geiser#201]
When writing/editing scheme (chicken, racket so far) the debugger pops up at inopportune times. It appears to be caused by thinking a function is incorrect because it is not yet completed. For example, this issue often happens when I have typed: `(define )` and am trying to think of a name. The debugger pops up and my cursor switches to that buffer. It has a very negative impact on my ability to think while programming.

I am using `GNU Emacs 25.1.50.1 (x86_64-apple-darwin15.5.0, NS appkit-1404.47 Version 10.11.5 (Build 15F34)) of 2016-05-25`

geiser-version just returns `@PACKAGE_STRING@`

**Comment by jaor** [comment]
how have you installed geiser?  what's the contents of the "debugger"?
and its buffer name?

**Comment by randre03** [comment]
Geiser is installed. Buffer name is "Backtrace" and while it's contents change depending on situation here is an example of its recent contents:

`Debugger entered: ((2854 2856))
semantic--tag-expand((2854 2856))
semantic-repeat-parse-whole-stream(((punctuation 1 . 2) (symbol 2 . 6) (symbol 7 . 13) (semantic-list 14 . 35) (semantic-list 37 . 337) (semantic-list 339 . 741) (semantic-list 743 . 1270) (semantic-list 1272 . 1814) (semantic-list 1816 . 1851) (semantic-list 1853 . 1958) (semantic-list 1960 . 2484) (semantic-list 2486 . 2565) (semantic-list 2567 . 2723) (semantic-list 2725 . 2763) (semantic-list 2764 . 2804) (semantic-list 2806 . 2852) (semantic-list 2854 . 2856)) nil nil)
semantic-parse-region-default(1 2856 nil nil nil)
semantic-parse-region(1 2856)
semantic-fetch-tags()
semantic-fetch-tags()
semantic-idle-scheduler-refresh-tags()
semantic-idle-core-handler()
semantic-idle-scheduler-function()
apply(semantic-idle-scheduler-function nil)
timer-event-handler([t 0 1 0 t semantic-idle-scheduler-function nil idle 0])`

Now I am wondering if semantic is the issue here???

**Comment by jaor** [comment]
yes, it looks like a bad interaction with the semantic package.  geiser
does not use semantic in any way, so i'm guessing semantic is trying to
do something like (maybe) showing documentation via eldoc.  for what i
see in that backtrace, the error is entirely in semantic's code, so it's
hard for me to help here... i guess you know that `M-x toggle-debug-on-error`
will skip the buffer pop-ups, but you'll still have errors flashing...

**Comment by randre03** [comment]
Thanks. sorry for creating an unrelated issue.
