### ISSUE TITLE
edit identifier at point, MIT Scheme

### ISSUE THREAD

**Issue by feldman4** [jaor/geiser#204]
Similar to #160, but with MIT Scheme. 

I copied the same example into `test.scm` and compiled/loaded it with C-c C-k. Auto-doc works, but M-. on `fbe-fact` gives the "Couldn't find edit location for 'fbe-fact'" error.

INFO: REQUEST: <12>: (geiser:load-file "/Users/feldman/Google Drive/docs/classes/6.945/test.scm")

INFO: RETORT: ((error (key . retort-syntax)) (output . "
;Loading \"test.scm\"... done
;Value: fbe-fact

1 (user) => "))

INFO: <12>: processed

INFO: REQUEST: <13>: (geiser:eval '#f '(geiser:autodoc '(fbe-fact fbe-fact * if define)))

INFO: <13>: processed

INFO: REQUEST: <14>: (geiser:eval '#f '(geiser:symbol-location (quote fbe-fact)))

INFO: RETORT: ((result "((\"name\" . fbe-fact) (\"file\") (\"line\"))") (output . ""))

INFO: <14>: processed

INFO: REQUEST: <15>: (geiser:eval '#f '(geiser:module-location (quote (fbe-fact (fbe-1- n)))))

INFO: RETORT: ((result "((\"name\" fbe-fact (fbe-1- n)) (\"file\") (\"line\"))") (output . ""))

INFO: <15>: processed

**Comment by jaor** [comment]
i'm afraid `M-.` cannot work in MIT Scheme because MIT Scheme does not
offer source code locations in its runtime, and geiser relies on that
information coming from the scheme process.

**Comment by feldman4** [comment]
Is it possible to apply something like the following (from the docs) to known source files?

> Sometimes, the underlying Scheme will tell Geiser only the file where the symbol is defined, but Geiser will use some heuristics (read, regular expressions) to locate the exact line and bring you there.

**Comment by jaor** [comment]
i might be misremembering, but i'm almost sure MIT Scheme cannot even
tell the file...

**Comment by ecraven** [comment]
There is a way to get the file for compiled procedures:

(define (find-file+position-of-definition object name)
  (let ((file
         (if (and (entity? object)
                  (procedure? object))
             (receive (a b) (compiled-entry/filename-and-index (entity-procedure object)) a)
             (if (compiled-procedure? object)
                 (receive (a b) (compiled-entry/filename-and-index object) a)
                 #f))))
    (let ((scm-file (if (and file
                             (string-suffix? ".inf" file))
                        (string-append (substring file 0 (- (string-length file) 3)) "scm")
                        file)))
      (if (and scm-file
               (file-exists? scm-file))
          (find-definition-position-in-file scm-file object name)
          (let ((scm-file (if scm-file (find-mit-scheme-sources-file scm-file) #f)))
            (if (and scm-file
                     (file-exists? scm-file))
                (find-definition-position-in-file scm-file object name)
                'nil))))))

(define (find-definition-position-in-file file object name)
  (define (find-pos file object)
    (let ((file-lines (read-file-lines file)))
      (let loop ((lines file-lines)
                 (count 0))
        (if (null? lines)
            (values 0 "")
            (let ((match (re-string-search-forward (string-append ".*(define.* (?" name) (car lines))))
              (if match
                  (values count (car lines))
                  (loop (cdr lines)
                        (+ count (string-length (car lines)) 1)))))))) ;; 1 for new-line
  (receive (pos snippet)
      (find-pos file object)
    `((,(string-append "(define " name ")")
       (:location
        (:file ,file)
        (:position ,(+ 1 pos)) ;; extra new-line
        (:snippet ,snippet)
        )))))

This kind of works for some places in my local swank, but ymmv.

Greetings, Peter

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/204
