### ISSUE TITLE
Autodoc doesn't work for variables in MIT-Scheme

### ISSUE THREAD

**Issue by sunqingyao** [jaor/geiser#205]
I'm using Emacs 26, the latest version of Geiser, and MIT-Scheme 9.2, under macOS Sierra.

The problem is that **geiser-autodoc-mode** isn't working for user-defined variables:

![screen shot 2017-02-14 at 22 11 33](https://cloud.githubusercontent.com/assets/13443062/22932529/3533bdc8-f303-11e6-830a-0bf44cf3e04c.png)

I got nothing even if I call `geiser-autodoc-show` explicitly. However, for user-defined functions it works as expected:

![screen shot 2017-02-14 at 22 11 20](https://cloud.githubusercontent.com/assets/13443062/22932507/1e923b94-f303-11e6-95cf-02a17dc97b43.png)

BTW: Geiser is **AWESOME**!!!

**Comment by jaor** [comment]
@ecraven is this something that should work?

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/205
