### ISSUE TITLE
Racket scheme implementation with geiser is very slow when the user is typing

### ISSUE THREAD

**Issue by ryukinix** [jaor/geiser#224]
I don't have problem with geiser with the guile scheme implementation , however writing racket is pretty slow for me using geiser. Not even on disabling the company-mode for auto-completion make it better. However disabling flycheck I have a great improvement. Maybe flycheck is much agressive? But why only on racket? There is something special about that?

I'm running on Arch Linux with `4.9.58-2-lts` kernel version, `geiser-20170704.1044` and Racket `v6.10.1`.

**Comment by jaor** [comment]
i don't use flycheck, and geiser has no code that direclty relates to
it.  my best guess is that generation of completion lists in racket is
much slower than in guile (or there are many more completion candidates
on average): looking for completions is implemented on the scheme side.

**Comment by ryukinix** [comment]
I understand. Seems that flycheck doesn't have a proper linter for racket, so they simple execute the code... that is explain why is so slow. There is no problem at all, thinking better this is not related to `geiser` really, sorry for opening that. 

But you can help me to find a function on your repository which always be called when a user chooses the racket implementation from `geiser-set-scheme` prompt?

I'm trying do that:

```elisp
;; make flycheck on racket less agressive
(defun cooldown-flycheck-on-racket (impl)
  (message "debug: %s" impl)
  (when (equal impl "racket")
    (setq-local 'flycheck-check-syntax-automatically '(save mode-enabled))))

(advice-add 'geiser-impl--load-impl :after 'cooldown-flycheck-on-racket)
```

This will cut the good annoying part of flycheck being agressive disabling `idle` syntax check and `new-line` too. But it's not working (the advice it's not been called)

But unfortunately this function `geiser-impl--load-impl` seems not executed every theme. My idea is get the `impl`variable  and when it's bind to `"racket"` force cooldown on flycheck on the buffer with my `cooldown-flycheck-on-racket`.

**Comment by jaor** [comment]
can't you advise geiser-set-scheme-prompt itself?  in the :after
advice you'll have the implementation symbol at hand, and that function
has the scheme buffer as its current buffer.

and for cases where racket is automatically detected by geiser, you can
unset flycheck in a function added to geiser-mode-hook.

**Comment by ryukinix** [comment]
Actually yes, I can. I was thinking in a hard way getting the parameters of the function. Thanks for the idea! The final code as @jaor suggested is here:

```
(require 'geiser)
(require 'geiser-impl)

(defun cooldown-flycheck-on-racket (&rest _)
   (if (eq geiser-impl--implementation 'racket)
       (setq-local flycheck-check-syntax-automatically '(save mode-enabled))
     (setq flycheck-check-syntax-automatically (default-value 'flycheck-check-syntax-automatically))))

(advice-add 'geiser-set-scheme :after 'cooldown-flycheck-on-racket)
(add-hook 'geiser-mode-hook 'cooldown-flycheck-on-racket)
```

 Great piece of software, btw. Thank for supporting so nicely various scheme implementation for emacs!

**Comment by ryukinix** [comment]
I'm closing this issue since this is not related exactly to geiser, as we conclude.
