### ISSUE TITLE
Geiser + Guile : No Geiser REPL for this buffer. 

### ISSUE THREAD

**Issue by 83bytes** [jaor/geiser#227]
I get the message "No Geiser REPL for this buffer. Try running M-x run-geiser" even though a REPL is already running and I can use C-x C-e to evaluate small procedures from other buffers.

What should I do ?

**Comment by 83bytes** [comment]
Okay so!

Using C-c C-s and selecting `guile` helped and it works fine now. 

But I am wondering why was it not working before specfying the Scheme implementaion for that buffer. 

I have other buffers running too which work fine.

Am I missing something ?

**Comment by jaor** [comment]
> Okay so!
>
> Using C-c C-s and selecting guile helped and it works fine now.
>
> But I am wondering why was it not working before specfying the Scheme
> implementaion for that buffer.

the logic geiser follows to assign a scheme implementation to a buffer
is described here:

     http://geiser.nongnu.org/geiser_4.html#The-source-and-the-REPL

(along with ways of tweaking it).  if according to that logic the buffer
should have guile as its scheme, we must have a bug somewhere....

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/227
