### ISSUE TITLE
Geiser not ready for GNU Emacs 24.3.1 (when it's announced to support GNU Emacs 23.2 or later)

### ISSUE THREAD

**Issue by rcray** [jaor/geiser#231]
My version: GNU Emacs 24.3.1 (i386-mingw-nt6.2.9200) of 2013-03-17 on MARVIN.  I tried installing geiser through MELPA: M-x package-install RET geiser RET.  It seems to miss subr-x.  How can I get around the problem?

(*) Log

Leaving directory `c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901'

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-autodoc.el at Sat Nov 25 11:57:59 2017
Entering directory `c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/'

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-base.el at Sat Nov 25 11:57:59 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-chez.el at Sat Nov 25 11:57:59 2017
geiser-chez.el:111:31:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-chibi.el at Sat Nov 25 11:57:59 2017
geiser-chibi.el:111:31:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-chicken.el at Sat Nov 25 11:57:59 2017
geiser-chicken.el:304:31:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-company.el at Sat Nov 25 11:58:00 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-compile.el at Sat Nov 25 11:58:00 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-completion.el at Sat Nov 25 11:58:00 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-connection.el at Sat Nov 25 11:58:00 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-custom.el at Sat Nov 25 11:58:00 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-debug.el at Sat Nov 25 11:58:00 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-doc.el at Sat Nov 25 11:58:00 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-edit.el at Sat Nov 25 11:58:00 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-eval.el at Sat Nov 25 11:58:00 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-guile.el at Sat Nov 25 11:58:00 2017
geiser-guile.el:413:31:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-image.el at Sat Nov 25 11:58:00 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-impl.el at Sat Nov 25 11:58:01 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-log.el at Sat Nov 25 11:58:01 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-menu.el at Sat Nov 25 11:58:01 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-mit.el at Sat Nov 25 11:58:01 2017
geiser-mit.el:19:1:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-mode.el at Sat Nov 25 11:58:01 2017
geiser-mode.el:14:1:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-popup.el at Sat Nov 25 11:58:01 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-racket.el at Sat Nov 25 11:58:01 2017
geiser-racket.el:423:31:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-reload.el at Sat Nov 25 11:58:01 2017
geiser-reload.el:14:1:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-repl.el at Sat Nov 25 11:58:01 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-syntax.el at Sat Nov 25 11:58:02 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-table.el at Sat Nov 25 11:58:02 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-version.el at Sat Nov 25 11:58:02 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-xref.el at Sat Nov 25 11:58:02 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser.el at Sat Nov 25 11:58:02 2017

Compiling no file at Sat Nov 25 12:02:41 2017
Leaving directory `c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901'

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-autodoc.el at Sat Nov 25 12:02:41 2017
Entering directory `c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/'

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-base.el at Sat Nov 25 12:02:41 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-chez.el at Sat Nov 25 12:02:41 2017
geiser-chez.el:111:31:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-chibi.el at Sat Nov 25 12:02:41 2017
geiser-chibi.el:111:31:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-chicken.el at Sat Nov 25 12:02:41 2017
geiser-chicken.el:304:31:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-company.el at Sat Nov 25 12:02:42 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-compile.el at Sat Nov 25 12:02:42 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-completion.el at Sat Nov 25 12:02:42 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-connection.el at Sat Nov 25 12:02:42 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-custom.el at Sat Nov 25 12:02:42 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-debug.el at Sat Nov 25 12:02:42 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-doc.el at Sat Nov 25 12:02:42 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-edit.el at Sat Nov 25 12:02:42 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-eval.el at Sat Nov 25 12:02:42 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-guile.el at Sat Nov 25 12:02:42 2017
geiser-guile.el:413:31:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-image.el at Sat Nov 25 12:02:43 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-impl.el at Sat Nov 25 12:02:43 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-log.el at Sat Nov 25 12:02:43 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-menu.el at Sat Nov 25 12:02:43 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-mit.el at Sat Nov 25 12:02:43 2017
geiser-mit.el:19:1:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-mode.el at Sat Nov 25 12:02:43 2017
geiser-mode.el:14:1:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-popup.el at Sat Nov 25 12:02:43 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-racket.el at Sat Nov 25 12:02:43 2017
geiser-racket.el:423:31:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-reload.el at Sat Nov 25 12:02:44 2017
geiser-reload.el:14:1:Error: Cannot open load file: subr-x

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-repl.el at Sat Nov 25 12:02:44 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-syntax.el at Sat Nov 25 12:02:44 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-table.el at Sat Nov 25 12:02:44 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-version.el at Sat Nov 25 12:02:44 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-xref.el at Sat Nov 25 12:02:44 2017

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser.el at Sat Nov 25 12:02:44 2017

Compiling no file at Sat Nov 25 12:07:56 2017
Leaving directory `c:/users/daniel/emacs/.emacs.d/elpa/subr+-20170501.916'

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/subr+-20170501.916/subr+-pkg.el at Sat Nov 25 12:07:56 2017
Entering directory `c:/users/daniel/emacs/.emacs.d/elpa/subr+-20170501.916/'

Compiling file c:/users/daniel/emacs/.emacs.d/elpa/subr+-20170501.916/subr+.el at Sat Nov 25 12:07:56 2017

Compiling no file at Sat Nov 25 12:16:47 2017

**Comment by jaor** [comment]
On Mon, Nov 27 2017, rcray wrote:

> My version: GNU Emacs 24.3.1 (i386-mingw-nt6.2.9200) of 2013-03-17 on
> MARVIN. I tried installing geiser through MELPA: M-x package-install
> RET geiser RET. It seems to miss subr-x. How can I get around the
> problem?

subr-x is only explicitly used in geiser for MIT in geiser-mit.  it
should be required only with eval-when-compile and that's wrong: i've
pushed a patch to the git repo where that's fixed: sooner or later it'll
reach melpa and you can try again... that said, i see that error in many
other places of your trace below where geiser subr-x is not explicitly
required by geiser, so it might be some of its dependencies causing the
problem, even with my latest patch.

if that is so, probably a way of getting around the problem is to use
geiser directly from a git checkout, without installing it.  you can see
how to do that here:

   http://geiser.nongnu.org/geiser_2.html#From-the-source_0027s-mouth

(it's pretty easy, you just need to add a `(load-file ..)` to your
.emacs).  if you give that a try, please don't forget to uninstall first
the melpa version to avoid conflicts.

(disclaimer: i've never used or tested geiser in a windows machine, so
the real problem could be totally different).

**Comment by rcray** [comment]
Something odd just happened.  I checked whether I had left geiser from MELPA installed.  I had not.  I followed the instructions to download geiser from the git repository, added (load-file "~/geiser/elisp/geiser.el") to my .emacs, evaluated the line and tried to run geiser.  I chose "racket" and it couldn't find racket.  I then searched for instructions and learned that I should (setq geiser-racket-binary "~/racket/racket.exe") in my .emacs.  I did it.  Geiser still couldn't find it.  I decided to restart EMACS then load geiser again.  When I did it, it now says ``Cannot open load file subr-x''.  Here's my *Messages*:

Loading c:/users/daniel/emacs/.recentf...done
Cleaning up the recentf list...
File c:/users/daniel/emacs/tmp/geiser/bin/geiser-racket.sh removed from the recentf list
File c:/users/daniel/emacs/tmp/geiser/bin/Makefile.am removed from the recentf list
File c:/users/daniel/emacs/.emacs.d/elpa/subr+-20170501.916/subr+-autoloads.el removed from the recentf list
File c:/users/daniel/emacs/.emacs.d/elpa/geiser-20171121.1901/geiser-autoloads.el removed from the recentf list
Cleaning up the recentf list...done (4 removed)
Loading c:/users/daniel/emacs/.quicklisp/slime-helper.el (source)...done
Loading c:/users/daniel/emacs/geiser/elisp/geiser.el (source)...done
For information about GNU Emacs and the GNU system, type C-h C-a.
Making completion list...
progn: Cannot open load file: subr-x

**Comment by jaor** [comment]
hmmm... could you please try with

   emacs --debug-init

it should give a bit more information on the error.  also, to make sure
none of your customizations i having any influence (not that i expect
them to have any, but one never knows), you could also try

   emacs -Q

and then manually eval (load-file "~/...") in the *scratch* buffer.

**Comment by rcray** [comment]
Here's the result.  I ran it as emacs --debug-init and also as emacs -Q --- same result.  Here's the `*Messages*`.

```
For information about GNU Emacs and the GNU system, type C-h C-a.
Mark set
Loading c:/users/daniel/emacs/geiser/elisp/geiser.el (source)...done
t
progn: Cannot open load file: subr-x

```

**Comment by jaor** [comment]
as far as i can tell, someone down the dependency chain is trying to use
subr-x.el and that seems to be unavailable in your emacs build: googling
a bit tells me that subr-x was introduced in emacs 24.4.  if that's the
case, i'm afraid i have no workaround other than trying a newer emacs
version.

**Comment by jaor** [comment]
a thing to try (if you're not interested in using MIT scheme) is editing
geiser.el and removing its autoload (i.e., deleting lines 110-12 in that
file): that's the only place where we explicitly require subr-x.

**Comment by jaor** [comment]
just in case the only culprit was geiser-mit, i've pushed a patch that
removes the explicit dependency on subr-x altogether (it was there to
use a rather simple function that can be inlined), so that you don't
need to edit geiser.el to try, just update your git checkout.

**Comment by rcray** [comment]
Updated repository, M-x geiser RET racket RET.

```
Welcome to Racket v6.6.
racket@> (+ 1 1)
2
racket@> 
```

I'm feeling taken care by very high excellence.  Thank you so much.

**Comment by jaor** [comment]
excellent.  thanks to you for your help and for keeping trying! :)
