### ISSUE TITLE
Documentation from Snow fort and chibi

### ISSUE THREAD

**Issue by arichiardi** [jaor/geiser#234]
Hi folks!

I have started yesterday to play with `chibi-scheme` and while it bootstraps fine in `geiser`, I really really miss documentation. I see that `geiser` has `C-c C-d i` for the manual and I was wondering whether the documentation browser could show the doc in http://snow-fort.org.

This might beneficial for the other schemes as well as it seems that the common repository of R7RS libs in the future is there (but don't say it too loud).

What do you think? Can this be a good idea?

**Comment by jaor** [comment]
sounds good to me, provided http://snow-fort.org is a good source (i
just clicked around and several links are giving me 502 errors, though).

**Comment by arichiardi** [comment]
Yep the `cyclone` ones are not correct. The `chibi` ones are good though. Seems a bit flaky at the moment for sure.

**Comment by dleslie** [comment]
http://schemers.org/ is generally a known-good for "standard" scheme documentation.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/234
