### ISSUE TITLE
add support for IronScheme

### ISSUE THREAD

**Issue by rolandoam** [jaor/geiser#235]
I would like to know how hard would it be to add support for [IronScheme](https://github.com/leppie/IronScheme) (running on mono). IronScheme already includes its own remote REPL support, so it should be easy to leverage this.

I wouldn't mind working on this, but it would be great if you can point me in the right direction :)

**Comment by jaor** [comment]
Hi Rolando,

Geiser works by running an instance of a REPL, or remotely connecting to
one, and evaluating the scheme code it sees there.  Then, everytime it
needs to perform some operation (like, say, printing autodoc, jumping to
a source location or expanding a macro), it asks the running scheme
instance for that information.  So supporting a new scheme usually means
writing a small scheme library that provides that information on demand,
and then some standard elisp functions that invoke the procedures in
that library.

To see what elisp functions need to be implemented, just execute the
command `M-x geiser-implementation-help` inside emacs with a recent
version of geiser installed.  And then take a look at, say,
geiser-guile.el or geiser-racket.el for examples of how those functions
are implemented for concrete schemes (those are the most featureful
implementations we have, so perhaps it's easier to begin with something
like geiser-chicken.el or geiser-chibi.el).

**Comment by rolandoam** [comment]
Thanks! I'll give that a try and if I have more questions I'll come back :)

**Comment by rolandoam** [comment]
Got the repl running inside emacs and also Emacs recognizes iron as a scheme. Next step: get eval working :)

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/235
