### ISSUE TITLE
Installed geiser, running M-x run-geiser results in error

### ISSUE THREAD

**Issue by chetnashah** [jaor/geiser#236]
All requirements in https://github.com/jaor/geiser#requirements are satisfied.
Installed geiser,

On running `M-x run-geiser`

Emacs error messages buffer shows
`defvar: Wrong number of arguments: (1 . 1), 2`

Version information of geiser: 20180130.1450

**Comment by alezost** [comment]
Could you do "M-x toggle-debug-on-error", repeat that error, and show the backtrace

**Comment by chetnashah** [comment]
The stacktrace is following:
```
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 2)
  completion-table-dynamic(geiser-completion--symbol-list t)
  (defvar geiser-completion--symbol-list-func (completion-table-dynamic (quote geiser-completion--symbol-list) t))
  require(geiser-completion)
  eval-buffer(#<buffer  *load*-179272> nil "/home/jayshah/.emacs.d/elpa/geiser-20180130.1450/geiser-company.el" nil t)  ; Reading at buffer position 500
  load-with-code-conversion("/home/jayshah/.emacs.d/elpa/geiser-20180130.1450/geiser-company.el" "/home/jayshah/.emacs.d/elpa/geiser-20180130.1450/geiser-company.el" nil t)
  require(geiser-company)
  eval-buffer(#<buffer  *load*> nil "/home/jayshah/.emacs.d/elpa/geiser-20180130.1450/geiser-repl.el" nil t)  ; Reading at buffer position 415
  load-with-code-conversion("/home/jayshah/.emacs.d/elpa/geiser-20180130.1450/geiser-repl.el" "/home/jayshah/.emacs.d/elpa/geiser-20180130.1450/geiser-repl.el" nil t)
  autoload-do-load((autoload "geiser-repl" "Start a Geiser REPL." t nil) run-geiser)
  command-execute(run-geiser record)
  #[257 "\304\305!\203\f\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"]("run-geiser")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "pkg-info-package-version" "pkg-info-version-info" "geiser" "list-packages" "cd" "5x5" "arp" "dbx" "dig" "erc" "ert" "eww" "ftp" "gdb" "irc" "jdb" "man" "mpc" "pdb" "pwd" "rsh" "sdb" "xdb" "calc" "diff" "dirs" "ffap" "gnus" "grep" "help" "ielm" "info" "life" "mail" "mpuz" "ping" "pong" "smex" "talk" "term" "undo" "yank" "zone" "align" "chmod" "debug" "diary" "dired" "ediff" ...) :predicate nil :require-match t :history counsel-M-x-history :action #[257 "\304\305!\203\f\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"] :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  call-interactively(counsel-M-x nil nil)
command-execute(counsel-M-x)
```

**Comment by jaor** [comment]
what's your emacs version?

**Comment by chetnashah** [comment]
Emacs 24.5.1 with Spacemacs 0.200.13@24.5.1 on Ubuntu 16.04.3 LTS.

**Comment by jaor** [comment]
i just pushed a patch to git that should fix the problem.  could you
please give it a try when you can? thanks!

**Comment by chetnashah** [comment]
Ok thanks, the package won't be available to melpa right now I think? 
In that case I should clone it to some dir? 
Sorry I am new to emacs package management.

**Comment by jaor** [comment]
On Sat, Feb 03 2018, chetna wrote:

> Ok thanks, the package won't be available to melpa right now I think?

there's a delay, but i'm not sure how long it is.  i *think* it should
be long.

> In that case I should clone it to some dir?

if it takes too long, please see
http://www.nongnu.org/geiser/geiser_2.html#From-the-source_0027s-mouth
... for a quick check, you don't need to compile anything, just git
clone and the first step in "Setting it up" (probably you'll need to
uninstall the melpa package first, though).

**Comment by chetnashah** [comment]
Yes, Thanks a lot! 🙏
works nicely with new source.
I've used geiser previously and 
I must say it is a wonderful and productive experience for beginners!

**Comment by dieggsy** [comment]
@jaor @chetnashah melpa rebuilds every 4 hours with a 10 minute pause in between IIRC
