### ISSUE TITLE
Missing stdout generated by ffi calls

### ISSUE THREAD

**Issue by tumdum** [jaor/geiser#237]
I have this small c file:
```c
    #include <stdio.h>
     
    void f1(void) {
      printf("f1 called\n");
    }
```
Which can be compiled into shared library with this command:
```bash
gcc lib.c -fpic -shared -o libx.so
```
I use this library in small Racket program:
```racket
    #lang racket
     
    (require ffi/unsafe
             ffi/unsafe/define)
     
    (define-ffi-definer define-x (ffi-lib "/home/klak/Developer/racket-ffi/libx.so"))
     
    (define-x f1 (_fun -> _void))
     
    (void (f1))
```
When I runt that script via command line repl I can see output from f1:
```
$ racket
Welcome to Racket v6.12.
> ,enter "main.rkt"
f1 called
"main.rkt"> (f1)
f1 called
"main.rkt"> (void (f1))
f1 called
"main.rkt">
```
Running this under geiser [does not show stdout](https://imgur.com/a/LSfqw).

**Comment by jaor** [comment]
hmm, it works fine for me, i see the output:


     Welcome to Racket v6.12.
     racket@> ,enter "/home/jao/tmp/test.rkt"
     f1 called
     racket@test.rkt> (f1)
     f1 called
     racket@test.rkt> 

i am not sure what might be causing the problem for you... i'm on
gnu/linux, so maybe there's something related to that...

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/237
