### ISSUE TITLE
Org files can easily be converted into Markdown

### ISSUE THREAD

**Issue by mettacrawler** [jaor/geiser#243]
Hi Sir,

The README on the GitHub web site has some cosmetic issues (and copy-pasting issues) which are easy to fix; you can simply use [(org-md-export-to-markdown)](https://orgmode.org/manual/Markdown-export.html) to generate README.md using README as source code.

Admittedly, you will run into the issue of GitHub selecting the first README in the git tree where "first" is determined by asciibetical order.  Renaming README to README.org will allow README.md to be displayed in the GitHub web page.

I have an example of a generated file here:
https://github.com/mettacrawler/geiser/blob/master/README.md

I do not know if it would make sense to do a pull request for this.

Thank you,
MC

**Comment by mettacrawler** [comment]
Specifically, if you try to copy-paste this line from the GitHub web site README (the org README)
`(setq geiser-active-implementations ‘(chicken guile))`

The quote mark is a Unicode character.  

The converted version is ASCII.
`(setq geiser-active-implementations '(chicken guile))`

**Comment by jaor** [comment]
hmm. i'd prefer not to include a generated file in the repo, specially
when github also knows how to display org files.  can't be just fix the
cosmetic issues in the org file without generating markdown?

**Comment by mettacrawler** [comment]
I think that https://github.com/wallyqs/org-ruby isthe conversion software that GitHub uses.

The README.md in https://github.com/github/markup points to that Ruby code converter.

The [README.org](https://raw.githubusercontent.com/wallyqs/org-ruby/master/README.org) in the org-ruby git tree is full of markdown codes like
```
#+BEGIN_SRC sh
```
How do you feel about someone putting such markdown in the README.org of this project?

**Comment by jaor** [comment]
On Mon, Apr 02 2018, mettacrawler wrote:

> #+BEGIN_SRC sh
>
> How do you feel about someone putting such markdown in the README.org
> of this project?

yes, that's definitely needed... i did some of it just a few minutes
ago.  when it comes to the keystrokes tables, either the org parser has
some glitches or i am missing something, because it inserts boldface in
a couple places for apparently no good reason.

do you see any other pending issues with the org markup after my
changes?

**Comment by mettacrawler** [comment]
Some of the table entries are centered.  Not sure why yet but this is an interesting example:

https://github.com/jaor/geiser/compare/master...mettacrawler:patch-1

**Comment by jaor** [comment]
it seems the parser is taking those lines for headers... i've introduced
separators as you suggested and the centering/boldface is gone

**Comment by mettacrawler** [comment]
Looks OK to me now.
