### ISSUE TITLE
autodoc (via company-quickhelp) not working with chez scheme

### ISSUE THREAD

**Issue by nosefouratyou** [jaor/geiser#245]
I currently have `autocomplete` working via company, but `autodoc` is not working with `company-quickhelp`. 

Here is what I have installed:
Ubuntu 17.10
GNU Emacs 25.2.2
Chez Scheme Version 9.5.1 
Geiser 20180329.548

Here is my setup:
```emacs-lisp
  (use-package geiser
    :ensure t
    :config
    (defvar geiser-active-implementations)
    (setq geiser-active-implementations '(chez))
    (setq geiser-mode-start-repl-p t)
    (setq geiser-repl-history-filename "~/.emacs.d/geiser-history")
    (add-to-list 'company-backends 'geiser-company))

(use-package company
    :ensure t
    :config
    (add-hook 'prog-mode-hook 'company-mode)
    (setq company-dabbrev-downcase 0)
    (setq company-idle-delay 0.3))

  (use-package company-quickhelp
    :ensure t
    :config
    (company-quickhelp-mode 1)
    (define-key company-active-map (kbd "C-c h") #'company-quickhelp-manual-begin))
```

and the error I get is:

> Error running timer ‘company-quickhelp--show’: (error "No buffer named No documentation available for ’default-exception-handler’")

And here is a screenshot of the autodoc failure:
![screenshot from 2018-04-09 19-38-15](https://user-images.githubusercontent.com/27776051/38528418-9e14fe14-3c2d-11e8-9fc6-9dcb5ec22258.png)

**Comment by jaor** [comment]
this might well be due to Chez itself not providing any way of obtaining doc locations or strings programmatically, but i'm not sure.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/geiser/issues/245
