### ISSUE TITLE
"Geiser default implementation" is ignored

### ISSUE THREAD

**Issue by zilti** [jaor/geiser#247]
As the title says. I've set it to `chicken`, but whenever I open an .scm file, the buffer defaults to Guile.

**Comment by dleslie** [comment]
That's the default, but it's being overridden by the implementation auto-detection. Confusing.

**Comment by dleslie** [comment]
You can force it by putting this at the top of the file:

``;; -*- geiser-scheme-implementation: 'chicken -*-

**Comment by zilti** [comment]
My workaround for now is that I've changed the order of the implementations in `Geiser Active Implementations` so Chicken is at the top. Also, thanks for the variable name.

**Comment by jaor** [comment]
to make chicken the one and only, one can customize
geiser-active-implementations, or provide a more complicated
auto-detection function.

i see how this is confusing and how geiser-fallback-implementation would
have been a better name for this variable, but the behaviour is as
intended.

**Comment by zilti** [comment]
I see. So my "workaround" is actually the correct solution. Maybe this would be an information to add to the option "docstring"?

**Comment by jaor** [comment]
On Mon, Apr 23 2018, Daniel Ziltener wrote:

> I see. So my "workaround" is actually the correct solution. Maybe this
> would be an information to add to the option "docstring"?

yes, definitely. and maybe the wording in the user manual should be
clearer?
