### ISSUE TITLE
Cannot get output with Chez scheme

### ISSUE THREAD

**Issue by gochit** [jaor/geiser#248]
Hi,

I'm using Geiser to get output from org-babel code block. This function works fine with guile and racket, but I cannot get it works with chez scheme.

When I create a code block with this simple display code:
```
#+BEGIN_SRC scheme :results output
  (display "Test string")
#+END_SRC
```
The *Geiser dbg* buffer only shows this result when I was using Chez:
```


=> #<void>



```

Mean while, it show this when I was using Guile and Racket.
```
(display "Test string")



=> #<void>

Test string
```

Could you show me how to get the output from Chez REPL?
Thank you so much

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/geiser/issues/248
