### ISSUE TITLE
Guile 1.8.8

### ISSUE THREAD

**Issue by ateymuri** [jaor/geiser#249]
Is there any way to use guile 1.8.8 with geiser? Some other systems like Lilypond ask for guile 1.8.

**Comment by jaor** [comment]
> Is there any way to use guile 1.8.8 with geiser? Some other systems
> like Lilypond ask for guile 1.8.

hmmm, most probably not, i'm afraid: we don't keep backwards
compatibility.  the only way would be to use an older geiser version
(which in the case of guile might not be as bad as it sounds, since it's
the best supported implementation).

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/geiser/issues/249
