### ISSUE TITLE
Emacs hangs when trying to eval the following definition in Guile 2.2.3

### ISSUE THREAD

**Issue by MaliRemorker** [jaor/geiser#250]
System:
* Debian Buster with Emacs 25.2.1
* Guile 2.2.3 
* Geiser 20180413.1646 from melpa-unstable

The following block of code froze Emacs for a long time
```scheme
    (define* (snap-cont dir #:key (fnm "snap"))                                                                                                                                   
      (let ((m (make-regexp (s+ fnm "\.s([0-9]+)"))))                                                                                                                             
        (scandir dir (lambda (f)                                                                                                                                                  
          (regexp-exec m (basename f))))))
```
after it was evaluated with `C-x C-e`. Even after Emacs unfroze, interaction was completely messed up (simple navigation froze and nothing could be evaluated anymore)

I have ivy-mode, company-mode, paredit-mode enabled alongside Geiser in a typical Guile session.

**Comment by MaliRemorker** [comment]
The issue persists even after disabling ivy and company in the buffer.

**Comment by MaliRemorker** [comment]
I have isolated the issue to be the regexp string: "\.s([0-9]+)". Once it is substituted with empty string "", Geiser evaluates the expression without issues.

**Comment by jaor** [comment]
thanks for the info, and for zeroing in the problem! i'm traveling and
cannot look into it right now, but will when i'm back!

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/geiser/issues/250
