### ISSUE TITLE
Don't comint-kill-region in geiser-repl--sentinel

### ISSUE THREAD

**Issue by dieggsy** [jaor/geiser#251]
With certain types of errors in Chicken Scheme, the repl cuts out and shows the message `It's been nice interacting with you!` while erasing the last input and error. I find this annoying, as I can't then examine the input that caused the error or the error output. This definition works better for me since it leaves those in the buffer before showing the message:

```emacs-lisp
(defun geiser-repl--sentinel (proc event)
  (let ((pb (process-buffer proc)))
    (when (buffer-live-p pb)
      (with-current-buffer pb
        (let ((comint-prompt-read-only nil)
              (comint-input-ring-file-name (geiser-repl--history-file))
              (comint-input-ring-separator geiser-repl--history-separator))
          (geiser-repl--on-quit)
          (push pb geiser-repl--closed-repls)
          (goto-char (point-max))
          ;; This was the problematic line
          ;; (comint-kill-region comint-last-input-start (point)) 
          (insert "\nIt's been nice interacting with you!\n")
          (insert "Press C-c C-z to bring me back.\n" ))))))
```

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/geiser/issues/251
