### ISSUE TITLE
Repository is not available on GitLab

### ISSUE THREAD

**Issue by raxod502** [jaor/geiser#252]
Going to https://gitlab.com/jaor/geiser gives a 404. Is the repository private?

**Comment by Purring** [comment]
Also related, please update the MELPA recipe when you do this too!

**Comment by jaor** [comment]
yes, sorry about that: it should now be public.  thanks for the heads
up!

**Comment by jaor** [comment]
On Sun, Jun 10 2018, Cody wrote:

> Also related, please update the MELPA recipe when you do this too!

https://github.com/melpa/melpa/pull/5547

**Comment by jaor** [comment]
@Purring i've also reverted the repo here to its previous state so that melpa users don't get an erroneous update while the PR is waiting.  sorry for the hassle.
