### ISSUE TITLE
Unable to enter guile module with #{42}# symbol

### ISSUE THREAD

**Issue by ghost** [jaor/geiser#32]
1. Create an empty file
2. Add (define-module (#{42}# foo))
3. Try entering it with C-c C-a

Expected: 
The REPL inside (#{42}# foo)

Happens: 
scheme@(guile-user)> ,m (42 foo)
While executing meta-command:
ERROR: In procedure module-local-variable: Wrong type argument in position 2 (expecting symbol): 42

AFAICS, Geiser strips #{}# from the module, tho they are necessary.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/32
