### ISSUE TITLE
a few #lang rackjure errors within geiser, due to custom #%app?

### ISSUE THREAD

**Issue by viperscape** [jaor/geiser#34]
I don't know how to explain this properly and may miss the mark, but when running a racket file with #lang rackjure I notice some things do not work and throw an error, as if the rackjure language import never happened. I spoke to @greghendershott and he explained it has something to do with the custom #%app and geiser and suggested I post an issue here. Running the same things directly at prompt in drracket seem fine.

Example:

```
#lang rackjure

{'k1 "value"}
```

should return

```
'((k1 . "value"))
```

but instead I receive an error both at prompt in geiser and if I evaluate the expression then geiser dbg prints an error.

```
{'k1 "value"}

Error: struct:exn:fail:contract

application: not a procedure;
 expected a procedure that can be applied to arguments
  given: 'k1
  arguments...:
   "value"
```

```
Welcome to Racket v6.0.
racket@> {'k1 "value"}
application: not a procedure;
 expected a procedure that can be applied to arguments
  given: 'k1
  arguments...:
   "value"
  errortrace...:
   stdin::43: ((quote k1) "value")
  context...:
   /home/chris/racket/collects/racket/private/misc.rkt:87:7
racket@> 
```

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/34
