### ISSUE TITLE
Howto abort evaluation in source file

### ISSUE THREAD

**Issue by lotabout** [jaor/geiser#36]
If we `eval` a loop in source file via `eval-definition`, is there a way to abort that evaluation? Or will we add this feature?

Thanks.

**Comment by dleslie** [comment]
There's not a good standard way to interrupt a Scheme REPL; I would suggest killing the process and relaunching it, but that would also discard all of the loaded definitions.

Something like the pseudo-code:

```elisp
(switch-to-geiser)
(kill-process)
(kill-buffer)
(run-geiser)
(message "Scheme REPL relaunched")
```

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/36
