### ISSUE TITLE
Wrong source for functions defined in letrec

### ISSUE THREAD

**Issue by omidmnz** [jaor/geiser#40]
I get "((guile):even? n)" by placing the cursor on the usage of even? function on the last line

``` scheme
(letrec ((even? 
          (lambda (n)
            (if (= n 0) #f (odd? (- n 1)))))
         (odd?
          (lambda (n)
            (if (= n 0) #t (even? (- n 1))))))
  (even? 1000))
```

, which should be "((guile-user):even? n)", like the one on the 2nd line of the following code.

``` scheme
(define (even? n) (if (= (remainder n 2) 0) #f #t))
(even? 1000)
```

My even? functions return #t if the given argument is odd, so one can easily double-check that it really is the user-defined function.
I am using geiser-20140531.1518, with Guile 2.0.11, and Emacs 24.3.1 on a 64 bit Linux machine.
Honestly, I'm not sure if it is a Geiser's bug, or Guile's. I reported it here, because I knew there is collaboration between two projects.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/40
