### ISSUE TITLE
Allow to set breakpoints and watchpoints from the source editor

### ISSUE THREAD

**Issue by memeplex** [jaor/geiser#42]
I think it shouldn't be that hard using guile traps api. I don't know about racket.

**Comment by dleslie** [comment]
Yep, this is on my radar as the next Emacs hackery I want to engage in, but I can't commit to a timeline.

**Comment by dleslie** [comment]
#54 would be relevant.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/42
