### ISSUE TITLE
[Petite]Cannot find petite implementation

### ISSUE THREAD

**Issue by ProfessorX** [jaor/geiser#44]
I have petite scheme downloaded and installed as guided by the <www.scheme.com> website. Then I config the geiser in Emacs as follows:
I put 
- `petite` in Geiser Active Implementation lists, below guile and racket.
- Restart Emacs.
- Press `C-C` and `C-S` in a scm file to set Scheme.

Then the Emacs told me _Cannot find petite implementation_ while in fact it is installed and working fine with command line. (Aka, I have Petite Scheme working in command line but I would like that to co-op with Emacs)

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/44
