### ISSUE TITLE
geiser-eval-last-sexp doersn't perform as expected

### ISSUE THREAD

**Issue by Txellenne** [jaor/geiser#50]
![cx-ce-doesnt-work](https://cloud.githubusercontent.com/assets/3199677/5893701/16b390d4-a4e6-11e4-9b36-24dba1357060.png)
Hi there, 
According manual `C-x C-e`  shoud make `geiser-eval-last-sexp` so `Eval sexp before point` but this doesn't happen in my case, any clue about what I'm, probably, overlooking, please?
[see screen shot attached](https://cloud.githubusercontent.com/assets/3199677/5893701/16b390d4-a4e6-11e4-9b36-24dba1357060.png)
I'd appreciate it,

**Comment by jaor** [comment]
there are too many possible causes, from not having a repl started to
not positioning the cursor at the end of a sexp or not having a working
geiser installed... can you describe what happens to you in more detail?

**Comment by jaor** [comment]
@Txellenne sorry, i hadn't seen your image.  Evaluation is working just fine: in Guile, when you evaluate a function definition, the returned value is `#<unspecified>`, as printed by Geiser, which means that the define did work, i.e., you should be able to call `factorial` afterwards.

Closing the issue: please feel free to reopen if i misunderstood.
