### ISSUE TITLE
`geiser-edit-symbol-at-point' does not work for Chicken

### ISSUE THREAD

**Issue by zhfuzzy** [jaor/geiser#52]
I had a look at the call-stack of `geiser-edit-symbol-at-point', it seems that the the chicken process can't return the (file, line ...) info of the symbol at point.

Is that I missed some eggs extension or something else?

(i've installed 'apropos', 'chickendoc', 'fmt' and 'symbol-utils'.Version: chicken 4.8.0.5, emacs 24.4 with latest geiser from melpa)

BTW,  is there any better solution for jumping in scheme source?

**Comment by jaor** [comment]
Dan will correct me if i'm wrong, but it think jumping to definitions is not supported by chicken because that's not an information that the interpreter can provide (source locations are computed by the scheme side in geiser).  maybe for cases like this we could fall back to some elisp-based solution (like using etags under the rug), but it's not trivial to implement (and it would be much less precise).

**Comment by JohnFarmer** [comment]
Got it, one more question.
In the defination of `geiser-edit-symbol-at-point', there is a command which ask for the source info from scheme interpreter.
(cmd `(:eval (:ge symbol-location ',symbol)))
Can you give me a hint on how can I find the _real command_ that geiser send to scheme interpreter? I'm completely lost in the expansion of `cmd'. 
I'll have some try and then ask chicken users for help if needed.

**Comment by jaor** [comment]
With `C-u M-x geiser-show-logs` you'll see in a buffer all the messages
that go back and forth between emacs and the scheme interpreter...

**Comment by dleslie** [comment]
Yep, Chicken cannot introspect as to where a symbol was defined.

However, GNU Global can parse Scheme files. Using geiser + ggtags does an OK job of filling this gap.

**Comment by dleslie** [comment]
Please assign this to me. :)

**Comment by dleslie** [comment]
@fangzhouuu If you're feeling adventurous, you can modify scheme/chicken/emacs/emacs.scm to set use-debug-log to #t, which will dump all the received actions and their results to a log file in your home directory.

**Comment by dleslie** [comment]
@jaor I wasn't aware that this discussion existed; in the future please alert me with an @dleslie tag, or drop me an email. ;)

**Comment by jaor** [comment]
@dleslie sorry about the lack of a ping (i just assumed that you were using github's "watch all" functionality).

we could perhaps implement `geiser-edit-symbol-at-point` for chicken (and other schemes with similar limitations) in terms of global under the rug, providing transparent tag file generation under the covers?

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/52
