### ISSUE TITLE
Geiser doesn't support (trace) and (untrace) statements

### ISSUE THREAD

**Issue by dleslie** [jaor/geiser#54]
Which is a somewhat common Scheme extension, and can be implemented for Schemes that lack it.

Likewise, (break) and (continue) and (unbreak) might be worth considering.

**Comment by jaor** [comment]
yes... i'd like to implement something in this area, perhaps in the fashion of edebug (similarly to what they've done recently in CIDER): C-u C-M-x to set trace/step on a function, and then breakpoints.  i'll give it a try in the following weeks, at least to put in place the generic elisp interface and a guile implementation (as an aside, i'm considering dropping racket support in favour of racket-mode).

**Comment by dleslie** [comment]
Before dropping support for Racket perhaps it's worthwhile to check for any present users in /r/Emacs, /r/Scheme, /r/Racket and the Racket user mailing lists or forums (not aware what these are, myself)?

**Comment by jaor** [comment]
yes, of course.

**Comment by dleslie** [comment]
IMHO, it seems to me that Geiser is for Scheme, whereas Racket has become post-scheme, and doesn't necessarily need to be constrained to a homoiconic grammar. Fully supporting Racket would be quite an undertaking, probably best left as a dedicated project.

**Comment by dleslie** [comment]
Relatedly, Chicken now has a built-in source-level visual debugger.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/54
