### ISSUE TITLE
Geiser doesn't support Gambit

### ISSUE THREAD

**Issue by dleslie** [jaor/geiser#56]
Though Gambit has some Emacs support in a minor mode, it doesn't have nearly as much utility available as Geiser can provide.

https://github.com/feeley/gambit/blob/master/misc/gambit.el

**Comment by dleslie** [comment]
Filed for posterity.

**Comment by ChrisBlom** [comment]
I've started an attempt to add gambit support [here](https://github.com/ChrisBlom/geiser/tree/feature/gambit). 
I'm just getting started, so far I got geiser to start a gambit repl process, but geiser failed to connect with this error in \*Messages\*

```
if: No prompt found!
or: No Geiser REPL for this buffer (try M-x run-geiser)```

**Comment by dleslie** [comment]
Good luck :)

I think you are taking the right path by copying and then modifying the Chicken port. Geiser is a little closer to Chicken than Guile or Racket.

**Comment by dleslie** [comment]
This was raised in:
https://github.com/part-cw/lambdanative/issues/74

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/56
