### ISSUE TITLE
Geiser REPL for CHICKEN doesn't number prompts sequentually

### ISSUE THREAD

**Issue by wasamasa** [jaor/geiser#58]
```
CHICKEN
(c) 2008-2014, The CHICKEN Team
(c) 2000-2007, Felix L. Winkelmann
Version 4.9.1 (rev 2b89724)
linux-unix-gnu-x86-64 [ 64bit manyargs dload ptables ]
compiled 2015-04-13 on odonien (Linux)

#;1> (+ 1 1)
2
#;16>
```

I find this behaviour a bit disconcerting as it suggests that there's fifteen interactions going on before receiving the next prompt.

edit: Using a minimal Emacs setup without `geiser-mode` stops this from happening.

**Comment by dleslie** [comment]
Woah, that's interesting.

**Comment by dleslie** [comment]
```scheme
CHICKEN
(c) 2008-2014, The Chicken Team
(c) 2000-2007, Felix L. Winkelmann
Version 4.9.0.1 (stability/4.9.0) (rev 8b3189b)
linux-unix-gnu-x86-64 [ 64bit manyargs dload ptables ]
bootstrapped 2014-06-07

#;1> (+ 1 1)
2
#;3> 
```

Confirmed.

**Comment by dleslie** [comment]
Actually, this sort of makes sense. Geiser makes a lot of invisible calls in order to do code inspection for smart completion et al. I've notice that Chicken can get rather bogged down with these, though. I'll poke at it.

**Comment by wasamasa** [comment]
I figured that this is what's going on.  If there's no further issue with it, I'd merely customize the prompt to make it less obvious.

Regarding code inspection, I'm afraid I've found another issue with completion, have to figure out a minimal reproduction example and open a ticket for that.

**Comment by dleslie** [comment]
Though the version hasn't been upped, master now includes some fixes for Chicken behaviour that -might- impact whatever you're testing.

**Comment by wasamasa** [comment]
As of #69, I only get these for the initial attempt at communicating with Chicken, from there on they're numbered sequentally.

**Comment by dleslie** [comment]
I'm not certain it's possible to fix the remaining instances.
