### ISSUE TITLE
geiser-doc-look-up-manual fails silently

### ISSUE THREAD

**Issue by sidhu1f** [jaor/geiser#60]
geiser-doc-look-up-manual fails silently with geiser 0.5, emacs 24.4.1 and guile 2.0.11. Work around is to start Info in emacs before invoking geiser-doc-look-up-manual.
Cause seems to be use of Info-find-file in geiser-guile.el. Perhaps a (require 'info) at the top of geiser-guile.el would be the right solution?

**Comment by jaor** [comment]
looking into this this week.  sorry for the long delay!

**Comment by Vifon** [comment]
I'm not sure if I'm experiencing the same issue but it's similar enough to warrant not opening a new issue.

When I call `geiser-doc-look-up-manual` it happily prints `Looking up manual for ’your-function’...` and then nothing happens. I'm using Racket v6.1, Geiser from MELPA and Emacs built from Git. Loading `info` does not help.

Any suggestions what I can do to further analyze the issue? I've tried using edebug but didn't get anything worthwhile.

**Comment by jaor** [comment]
racket does not have an info manual, so no info is opened and it's
normal that loading info has no effect... have you configured drracket's
help browser according to the indications in my previous response in
this thread?

**Comment by Vifon** [comment]
Yes, I did. DrRacket opens the documentation just fine. Now that you mention it, it makes sense that loading `info` doesn't change anything.

**Comment by jaor** [comment]
So it might be that the symbol you're asking docs for is not (yet)
defined, but that's strange... i'll take a look to see if i can
reproduce it.

**Comment by Vifon** [comment]
I'm trying to look up the symbols like `format` or `newline`. They definitely should be in the docs and DrRacket has no problem finding them.

**Comment by jaor** [comment]
you have a repl running, right?  this is what i do:

  - run-racket
  - open a file foo.rkt 
  - write
       #lang racket
       format
  - C-c C-d C-i

and emacs opens w3m for me just right (or whatever browser i've
specified in DrRacket's configuration)... what step is different for
you?

**Comment by Vifon** [comment]
I do everything the same as you but nothing happens. The only obvious difference is the browser (Chromium in my case). Normally I use `C-c C-z` to open the REPL for an already opened file but I've tried `run-racket` too.

**Comment by jaor** [comment]
if you go to the REPL and type: (help info) RET, what happens? that
should open the browser, and there there's no geiser intervention...

**Comment by Vifon** [comment]
Now it's getting interesting!

```
racket@> (help info)
Not found in any library's documentation: info
racket@> (help format)
Sending to web browser...
  file: /usr/share/doc/racket/reference/Writing.html
  anchor: (def._((quote._~23~25kernel)._format))
/bin/sh: 1: Syntax error: "(" unexpected
browser-run: process execute failed: '("chromium file:///usr/share/doc/racket/reference/Writing.html#(def._((quote._~23~25kernel)._format))")
```

I forgot to mention I'm on Ubuntu Server 15.04. `/bin/sh` is a symlink to `/bin/dash`, not `/bin/bash` as for instance on Arch. I've tried replacing it with a symlink to `/bin/bash` but I just got some other error (irrelevant, I suppose).

My `~/.racket/racket-prefs.rktd` contains this line:

```
(external-browser ("chromium " . ""))
```

**Comment by jaor** [comment]
i think your problem is that you have to quote the URL so that the shell
is not escaping it.  you could write a cromium.sh" shell script with
something like:

    #!/bin/bash

    exec chromium $*

**Comment by Vifon** [comment]
I've fixed the problem! It was indeed not Geiser after all. I've added a pair of quotes to the referenced racket-prefs line:

```
(external-browser ("chromium \"" . "\""))
```

Thanks a lot for your help and sorry for the confusion.
