### ISSUE TITLE
geiser-guile-manual-lookup-nodes problem

### ISSUE THREAD

**Issue by sidhu1f** [jaor/geiser#61]
When value of geiser-guile-manual-lookup-nodes is ("guile-2.0" "guile-library" ...) manual lookup for info nodes in "guile-2.0" works but not when value of geiser-guile-manual-lookup-nodes is ("guile-library" "guile-2.0" ...).

Manual lookup for "guile-library" does not work in either case (which may or may not be a geiser issue).

geiser 0.5, emacs 24.4.1, guile 2.0.11, debian jessie x86.

**Comment by jaor** [comment]
taking a look this week.  sorry for the long delay!

**Comment by sidhu1f** [comment]
Problem resolved, it was my misunderstanding, geiser works fine here. I mistakenly expected the info nodes to be directory names. But delving into geiser-guile--info-spec showed that node name "n" needs to be specified for filename "n.info.gz". Tested correct operation on geiser version 0.8.1.
