### ISSUE TITLE
broken link  in .../latest/

### ISSUE THREAD

**Issue by bremner** [jaor/geiser#62]
I get error 403 on this link

  http://download.savannah.gnu.org/releases/geiser/latest/geiser-0.7.tar.gz

I understand the file is downloadable from other places, but I'd have to rewrite the automation that checks for new versions

**Comment by jaor** [comment]
hmmm, maybe that's a temporary error? i'm getting a 302, as expected,
from here:

```console
[/tmp]$ curl -I  http://download.savannah.gnu.org/releases/geiser/latest/geiser-0.7.tar.gz
HTTP/1.1 302 Found
Date: Wed, 24 Jun 2015 12:29:36 GMT
Server: Apache/2.2.16 (Debian)
Location: http://download.savannah.gnu.org/releases-redirect/geiser/latest/geiser-0.7.tar.gz
Content-Type: text/html; charset=iso-8859-1

```

you see a 403 there?

**Comment by bremner** [comment]
jao <notifications@github.com> writes:

> hmmm, maybe that's a temporary error? i'm getting a 302, as expected,
> from here:
>
> ```console
> [/tmp]$ curl -I  http://download.savannah.gnu.org/releases/geiser/latest/geiser-0.7.tar.gz
> HTTP/1.1 302 Found
> Date: Wed, 24 Jun 2015 12:29:36 GMT
> Server: Apache/2.2.16 (Debian)
> Location: http://download.savannah.gnu.org/releases-redirect/geiser/latest/geiser-0.7.tar.gz
> Content-Type: text/html; charset=iso-8859-1
>
> ```

I get the 302, but it follows to a mirror where I get 403

╭─ maritornes:~/tmp 
╰─% wget http://download.savannah.gnu.org/releases/geiser/latest/geiser-0.7.tar.gz
--2015-06-24 14:52:54--  http://download.savannah.gnu.org/releases/geiser/latest/geiser-0.7.tar.gz
Resolving download.savannah.gnu.org (download.savannah.gnu.org)... 140.186.70.73
Connecting to download.savannah.gnu.org (download.savannah.gnu.org)|140.186.70.73|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://download.savannah.gnu.org/releases-redirect/geiser/latest/geiser-0.7.tar.gz [following]
--2015-06-24 14:52:54--  http://download.savannah.gnu.org/releases-redirect/geiser/latest/geiser-0.7.tar.gz
Reusing existing connection to download.savannah.gnu.org:80.
HTTP request sent, awaiting response... 302 Found
Location: http://mirror.unicorncloud.org/savannah-nongnu//geiser/latest/geiser-0.7.tar.gz [following]
--2015-06-24 14:52:54--  http://mirror.unicorncloud.org/savannah-nongnu//geiser/latest/geiser-0.7.tar.gz
Resolving mirror.unicorncloud.org (mirror.unicorncloud.org)... 144.76.58.182
Connecting to mirror.unicorncloud.org (mirror.unicorncloud.org)|144.76.58.182|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2015-06-24 14:52:55 ERROR 403: Forbidden.

╭─ maritornes:~/tmp 
╰─% curl -I http://mirror.unicorncloud.org/savannah-nongnu/geiser/latest/geiser-0.7.tar.gz
HTTP/1.1 403 Forbidden
Date: Wed, 24 Jun 2015 12:54:36 GMT
Server: Apache
Content-Type: text/html; charset=iso-8859-1

**Comment by jaor** [comment]
my final mirror works, but that's because it's a different one.  i'll
report the failing mirror to the savannah guys, although response times
from then tend to be long.  if this is not solved by the next release,
i'll simply host the tar.gz in github and call it a day: would that
solve the problem for you?

**Comment by bremner** [comment]
jao <notifications@github.com> writes:

> my final mirror works, but that's because it's a different one.  i'll
> report the failing mirror to the savannah guys, although response times
> from then tend to be long.  if this is not solved by the next release,
> i'll simply host the tar.gz in github and call it a day: would that
> solve the problem for you?

I expect so. I already download tarballs for at least one other project
for debian packaging, which (as you probably guessed) is what I'm after
here.

d

**Comment by jaor** [comment]
@bremner did perchance the problems with the savannah mirror go away?

**Comment by bremner** [comment]
jao <notifications@github.com> writes:

> @bremner did perchance the problems with the savannah mirror go away?

Yes, it seems fixed. Or at least it worked once ;).

d

**Comment by jaor** [comment]
okay... let's see if it still works in the forthcoming release and then
we can keep the gnu mirrors as the upstream link...

**Comment by dleslie** [comment]
Did it work? :wink:

**Comment by bremner** [comment]
Dan Leslie <notifications@github.com> writes:

> Did it work? :wink: 
>

Yes. although it's hard to be 100% since it was always mirror-dependant.

**Comment by jaor** [comment]
fwiw, as an alternative that does not seem to use a mirror, i'm using in
the web site http://download-mirror.savannah.gnu.org/releases/geiser/.

**Comment by dleslie** [comment]
I suppose this can be closed, then?
