### ISSUE TITLE
Geiser doesn't work with Racket Minimal 6.2

### ISSUE THREAD

**Issue by apg** [jaor/geiser#63]
Utilizing geiser-20150701.348 from Melpa, I get the following with an `M-x run-racket`

```
Welcome to Racket v6.2.
/home/apg/.emacs.d/elpa/geiser-20150701.348/scheme/racket/geiser/user.rkt:17:9: collection not found
  for module path: mzlib/thread
  collection: "mzlib"
  in collection directories:
   /home/apg/.racket/6.2/collects
   /usr/local/racket/collects
   /home/apg/.emacs.d/elpa/geiser-20150701.348/scheme/racket/
   /usr/local/racket/share/pkgs/racket-lib
  context...:
   show-collection-err
   standard-module-name-resolver
> 
```

It seems to be the case that mzlib/thread is deprecated in favor of just using racket/base. I'm guessing the full racket distribution includes a module that exports the new names as mzlib/thread.

**Comment by jaor** [comment]
i'll take another look, but last time we checked, racket/base didn't
provide all the needed functionality, and we had to give up on
supporting Racket Minimal... full racket included the full mzlib with
the missing functionality.

unless things have improved in racket/base, perhaps we could provide an
option for not loading the geiser module defining remote repls, and
support only pure comint repls for Racket Minimal.

**Comment by apg** [comment]
I'm looking into it now. racket/base provides `thread`. But, now I'm running into a srfi/13 problem. Probably will continue to hit a bunch of similar issues. :)

**Comment by apg** [comment]
So, actually, I don't even understand what Racket Minimal is for, as any legacy Racket code is every "legacy" Racket module I've encountered makes use of stuff that Minimal doesn't contain.

Perhaps the way forward is to minimize the deprecated modules in use, and at some point get to a point where Minimal works, but I'm thinking this is unnecessary for me right now.

**Comment by ryukinix** [comment]
There is no way to use racket-minimal with geiser? :/ so sad
