### ISSUE TITLE
cannot find Chicken REPL prompt on Windows

### ISSUE THREAD

**Issue by HappyBros** [jaor/geiser#67]
Geiser *is* able to find `csi.exe`; it's just not able to start the prompt. It may be from how the command to start the REPL is set:

>Emacs has builtin support for syntax-highlighting of Scheme code and running a Scheme interpreter in an interactive buffer. To use it with CHICKEN, add this to your ~/.emacs file:

> `(setq scheme-program-name "csi -:c")`

>The -:c is to force interactive mode, which is required on some platforms (most notably Windows).

> [Chicken Scheme Wiki](http://wiki.call-cc.org/emacs)

Running `csi.exe` on the Emacs shell causes an unresponsive buffer, while `csi.exe -:c` successfully launches it.  Hence, Geiser may need the `-:c` to launch the Chicken REPL.

**Comment by jaor** [comment]
you can try to set geiser-chicken-binary to '("csi.exe" "-:c"). that should
add the flag to the invocation of chicken.  in your .emacs:

```elisp
(setq geiser-chicken-binary '("csi.exe" "-:c"))
```

should do the trick...

**Comment by dleslie** [comment]
As luck would have it, I finally have a working Windows install again. I'll have a look.

**Comment by HappyBros** [comment]
> Chicken REPL up and running!
> -minibuffer

@jaor, that does do the trick. Closing the issue now. Thanks.

**Comment by dleslie** [comment]
This ought to be set as the default for Windows systems, because this will probably never be sufficient:
https://github.com/jaor/geiser/blob/master/elisp/geiser-chicken.el#L50

Can we reopen and assign to me? I'm swamped these weeks, but I'll have time soon, I hope.
