### ISSUE TITLE
problems running "make elpa" from release tarball

### ISSUE THREAD

**Issue by bremner** [jaor/geiser#78]
Please forgive filing two related issues as one. 

I'd like to use "make elpa" as part of the Debian packaging. Currently
this doesn't work, partly because I am building from the release
tarball, and partly because of some fussiness with /usr/bin/install on
Debian.

Problem 1: No README.elpa in release tarball.

╭─ maritornes:~/software/debian/geiser 
╰─ (git)-[upstream]-% ./configure
checking for a BSD-compatible install... /usr/bin/install -c
[snip]
config.status: creating doc/Makefile
╭─ maritornes:~/software/debian/geiser 
╰─ (git)-[upstream]-% make elpa
make: *** No rule to make target 'README.elpa', needed by 'elpa'.  Stop.

Problem 2: install gets angry about duplicated files?

╭─ maritornes:~/software/debian/geiser 
╰─ (git)-[upstream]-% touch README.elpa
╭─ maritornes:~/software/debian/geiser 
╰─ (git)-[upstream]-% make elpa        
Making info in .
[snip]
rm -rf /home/bremner/software/debian/geiser/geiser-0.7
/bin/mkdir -p /home/bremner/software/debian/geiser/geiser-0.7
echo '(define-package "geiser" "0.7" "GNU Emacs and Scheme talk to each other")' \
             > /home/bremner/software/debian/geiser/geiser-0.7/geiser-pkg.el
/usr/bin/install -c -m 644 /home/bremner/software/debian/geiser/elisp/*.el \
                        ./elisp/geiser-version.el \
                        /home/bremner/software/debian/geiser/geiser-0.7
/usr/bin/install: will not overwrite just-created ‘/home/bremner/software/debian/geiser/geiser-0.7/geiser-version.el’ with ‘./elisp/geiser-version.el’
Makefile:735: recipe for target 'elpa' failed
make: *** [elpa] Error 1

Neither of these is impossible to work around, but it would be even nicer if they could be fixed upstream.

**Comment by jaor** [comment]
i think the patch i just pushed fixes both problems... @bremner can you check if that's the case before a new release?

**Comment by bremner** [comment]
jao <notifications@github.com> writes:

> i think the patch i just pushed fixes both problems... @bremner can you check if that's the case before a new release?

Looks good.

d
