### ISSUE TITLE
geiser-connect-local broken for Guile

### ISSUE THREAD

**Issue by davexunit** [jaor/geiser#79]
Run the following Guile code:

```scheme
(use-modules (system repl server))
(spawn-server (make-unix-domain-server-socket #:path "/tmp/repl"))
```

In Emacs:

```lisp
(geiser-connect-local 'guile "/tmp/repl")
```

You can type at the REPL, but `<return>` and such do nothing and report error messages like:

```
geiser-repl--is-debugging: Invalid search bound (wrong side of point)
```

I'm using Geiser 0.7.

**Comment by jaor** [comment]
yes, i confirm this problem happens to me too, even with the current git head.  i'll take a look as soon as i can. thanks for the report!

**Comment by jaor** [comment]
I've pushed a patch that should address this issue.  Please, give it a try when you find a moment   Thanks!

**Comment by davexunit** [comment]
That did it!  Thanks!

Just for fun, here's the Guile module I used to build the latest Geiser using Guix:

```scheme
(define-module (gnu packages geiser)
  #:use-module (guix utils)
  #:use-module (guix packages)
  #:use-module (guix git-download)
  #:use-module (gnu packages)
  #:use-module (gnu packages autotools)
  #:use-module (gnu packages emacs)
  #:use-module (gnu packages texinfo))

(define-public geiser-git
  (package
    (inherit geiser)
    (name "geiser-git")
    (source (origin
              (method git-fetch)
              (uri (git-reference
                    (url "https://github.com/jaor/geiser.git")
                    (commit "4c06bb5")))
              (sha256
               (base32
                "0mc71s8pv5zb8xfycm9wxwbacw6brigiipv8z6d64g8c6zd3hgr1"))))
    (native-inputs
     `(("autoconf" ,autoconf)
       ("automake" ,automake)
       ("texinfo" ,texinfo)
       ,@(package-native-inputs geiser)))
    (arguments
     (substitute-keyword-arguments (package-arguments geiser)
       ((#:phases phases)
        `(modify-phases ,phases
           (add-after 'unpack 'autogen
                      (lambda _ (zero? (system* "sh" "autogen.sh"))))))))))
```

```
$ guix environment --ad-hoc emacs geiser-git -E "emacs -Q"
```

**Comment by jaor** [comment]
thanks for the fun, david :) is this something that one could submit to
the guix guys? does it make any sense to have it in the geiser repo?
(excuse the silly questions, i've never used guix).

**Comment by davexunit** [comment]
So, we have the stable version of Geiser packaged in Guix, which the
above recipe "inherits" from.  In general we prefer to stick to stable
release tarballs for our packages.  However, there's something I'd
like to encourage receptive developers to do: Put a `package.scm` file
in the root of their source tree that contains a Guix package
expression that can be used for two things.

1) Creating a development environment with all necessary dependencies
for hacking via `guix environment -l package.scm`

2) Installing development snapshots via `guix package -f package.scm`

If you're familiar with npm, think of like a much cooler, general
purpose `package.json`. :)

Here's an example of such a file for one of my own projects (pardon
the self-signed cert):

```scheme
(use-modules (guix packages)
             (guix licenses)
             (guix git-download)
             (guix build-system gnu)
             (gnu packages)
             (gnu packages autotools)
             (gnu packages guile))

(package
  (name "haunt")
  (version "0.1")
  (source (origin
            (method git-fetch)
            (uri (git-reference
                  (url "git://dthompson.us/haunt.git")
                  (commit "f012747")))
            (sha256
             (base32
              "0gj4xw79g3q87m6js0mbvv437zf7df5d2xg4sx65mpgc85j7zafs"))))
  (build-system gnu-build-system)
  (arguments
   '(#:phases
     (modify-phases %standard-phases
       (add-after 'unpack 'bootstrap
         (lambda _ (zero? (system* "sh" "bootstrap")))))))
  (native-inputs
   `(("autoconf" ,autoconf)
     ("automake" ,automake)))
  (inputs
   `(("guile" ,guile-2.0)))
  (synopsis "Functional static site generator")
  (description "Haunt is a static site generator written in Guile
Scheme.  Haunt features a functional build system and an extensible
interface for reading articles in any format.")
  (home-page "http://haunt.dthompson.us")
  (license gpl3+))
```

If you're interested, I could submit a patch that does this when I
have some more free time.

**Comment by jaor** [comment]
thanks for the explanation and the offer, david.  i'm definitely
interested in a PR. only a nit: i'd prefer if the package file would be
named guix.scm, guix-package.scm, guix.scm or something like that:
geiser's source tree is share by many "sort-of-packaging" systems...

**Comment by davexunit** [comment]
Sure!  The file's name can be whichever you prefer.

**Comment by jaor** [comment]
i'd use `guix.scm`  if there's no other preference from guix guys...

**Comment by davexunit** [comment]
That is fine.  The name is totally arbitrary.

**Comment by jaor** [comment]
excellent. closing this bug!
