### ISSUE TITLE
geiser-repl.el is loaded twice (circular dependency?)

### ISSUE THREAD

**Issue by alezost** [jaor/geiser#82]
Hello, I see that geiser modules require many other geiser modules.  And
I have a feeling that there are circular dependencies somewhere (it's
just a guess).  At least I noticed that `geiser-repl` is loaded twice
when `geiser-mode` is required.  I checked it by adding:

```elisp
(message "---- 'geiser-repl' is loaded ----")
```

to the very end of "geiser-repl.el".  Then I ran emacs, evaluated
`(require 'geiser-mode)` and I saw this string twice in the *Messages*
buffer.

This may lead to unpleasant consequences for users.  For example, if you
put the following into your `.emacs`:

```elisp
(with-eval-after-load 'geiser-repl
  (define-key geiser-repl-mode-map (kbd "C-c C-d") 'geiser-repl-exit))
```

and after starting emacs you open a scheme file, you will get the
following error:

    Key sequence C-c C-d m starts with non-prefix key C-c C-d

This happens because when `geiser-repl` is loaded the first time `C-c
C-d` key sequence is bound successfully, but then `geiser-repl` is
loaded again, and it tries to bind several `C-c C-d ...` documentation
keys but it's not possible anymore because `C-c C-d` is already bound.

To investigate where circularity may happen, I tried the following code:

```elisp
(defun require-message (feature &rest _)
  (message "Requiring %s" feature))

(advice-add 'require :before #'require-message)
```

But after evaluating `(require 'geiser-mode)` (in a freshly started
Emacs) I saw so many "Requiring geiser-…" messages, that... I decided to
open this issue :-)

**Comment by jaor** [comment]
we can try some linting tool.  i remember taking special care that no
circular dependencies occurred at all (i feel very strongly against
them), and actually geiser-reload kind of relies on that.  i thought the
byte compiler would emit warnings (if not plain errors) on
circularities, and i see none: shouldn't it?

**Comment by alezost** [comment]
Yes it should, but probably this is a more complex case.

I thought the problem might be that `geiser-impl` loads all
implementations.  So `geiser-repl` requires `geiser-impl`, it loads
guile/racket/chicken, and these modules also require `geiser-repl` (in
`define-geiser-implementation` macro).

So I commented the last line in `geiser-impl` (that loads
implementations) and found that `geiser-repl` was loaded only once after
requiring `geiser-mode`, but then at some point I got the error about my
"C-c C-d" binding.

Anyway, is loading all implementations really needed?  Since there are
autoloads for run-guile, switch-to-chicken, and other commands, I think
it is possible to remove this loading.

**Comment by jaor** [comment]
when running run-geiser/switch-to-geiser, we need to load the
implementations, otherwise they won't be found... perhaps we could
perform the loading dynamically when those functions are called, or just
wrap that line of code in an `(eval-after-load "geiser-repl" (mapc ...))` and 
put it in geiser.el... (busy right now to try thoroughly, but noting it
so that i don't forget)

**Comment by alezost** [comment]
I was just going to propose a patch for this when I saw your reply.  So
I have made a pull request (#87) that should solve it (at least my check
with `message` shows that `geiser-repl` is loaded only once).

As for the key binding issue I mentioned, I have not faced it anymore (after
disabling loading implementations in `geiser-impl.el`).  It was probably
a leftover or something.

**Comment by jaor** [comment]
okay, should be fixed know.  please @alezost, give it a look when you have a spare minute. thanks!

**Comment by alezost** [comment]
Yes, I think it is fixed, thank you!
