### ISSUE TITLE
Using defvar-local

### ISSUE THREAD

**Issue by alezost** [jaor/geiser#84]
Hello, I see Geiser uses the following forms:

```elisp
(make-variable-buffer-local
 (defvar ...))
```

Instead `(defvar-local ...)` may be used.  According to Emacs
NEWS this macro was introduced in 24.3.  So I'm wondering is
switching to `defvar-local` desired or do you prefer to keep a
backward compatibility with Emacs 23?

**Comment by jaor** [comment]
the original reason was to maintain compatibility with emacs 23... is
there any win using defvar-local besides the syntactic sugar? if it's
only aesthetics, doesn't feel like a good to break compat...

**Comment by alezost** [comment]
Yes, just aesthetics, thanks for the answer.  So I'm closing this
issue, sorry for bothering.

**Comment by jaor** [comment]
nothing to be sorry about. thanks for caring!
