### ISSUE TITLE
"M-x switch-to-geiser" error

### ISSUE THREAD

**Issue by alezost** [jaor/geiser#85]
Hello, if you call `M-x switch-to-geiser` in a "fresh" emacs (I mean
right after starting Emacs when Geiser has not been loaded yet) you'll
get an error:

    Wrong type argument: stringp, nil

This happens because it tries to run `run-geiser` with `nil`
implementation.

I think ideally it should either prompt for an implementation, or
alternatively say that this command should be used only on a running
REPL.

**Comment by jaor** [comment]
alex, how is geiser installed/loaded when you encounter that error?

**Comment by alezost** [comment]
I use geiser from the git repo.  So what I did:

1. emacs -Q

2. Evaluated the following:

   ```elisp
   (add-to-list 'load-path "/path/to/geiser/elisp")
   (require 'geiser)
   ```

3. M-x switch-to-geiser

And got that error.

**Comment by jaor** [comment]
ah, that's the problem.  the correct way to load geiser directly from
the repo is:

     (load-file (expand-file-name "/path/to/geiser/elisp/geiser.el"))

adding to load-path and require only work reliably in installed
versions.  see
http://geiser.nongnu.org/geiser_2.html#From-the-source_0027s-mouth for
all the details.

does it fix the problem for you?

**Comment by alezost** [comment]
Nope, did you try to reproduce it?:

1. emacs -Q

2. (load "/path/to/geiser/elisp/geiser.el")

3. M-x switch-to-geiser

AFAICT the same error would happen for geiser installed from melpa.

**Comment by jaor** [comment]
now i did reproduce it.  i'll look into it.

**Comment by jaor** [comment]
i just pushed a patch that should have fixed this one...

**Comment by alezost** [comment]
I see, thank you, so I'm closing this issue.
