### ISSUE TITLE
eldoc fails in Chicken with very large items

### ISSUE THREAD

**Issue by dleslie** [jaor/geiser#90]
Discovered as a result of investigating #64

Example, in a buffer or repl:

``` scheme
(define foo (make-list 10000 1))
```

`foo` will not consistently appear as an eldoc hint.

**Comment by dleslie** [comment]
I wonder if #104 fixed this...

**Comment by dleslie** [comment]
It did not; however, the el-doc fetch doesn't cause Emacs to halt, as it did before.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/90
