### ISSUE TITLE
Error starting REPL

### ISSUE THREAD

**Issue by zovt** [jaor/geiser#95]
```
Geiser requires racket version 5.3 but detected #f::2: read: expected a ')' to close '('
```

That is the error I am getting when I  run `run-geiser`. Any suggestions?

**Comment by dleslie** [comment]
Just wanted to say that I've seen this, but haven't had the time to try it yet.

**Comment by jaor** [comment]
what version of racket are you using, @zovt? (perhaps we broke something in the version check)

**Comment by zovt** [comment]
Whatever the latest was when I downloaded it. I was on Windows. It doesn't seem to be happening on *nix though.

**Comment by kovrik** [comment]
Having the same issue on Windows:
```
Starting Geiser REPL for racket ...
progn: Geiser requires racket version 5.3 but detected #f::2: read: expected a `)' to close `('
```

**Comment by jaor** [comment]
what version of geiser is this? 0.8.1? git?

**Comment by kovrik** [comment]
geiser-20151013.1153

**Comment by kovrik** [comment]
This line:
``` scheme
(geiser-repl--version 'racket (geiser-repl--binary 'racket))
```
Returns
```
#f::2: read: expected a `)' to close `('

```

**Comment by jaor** [comment]
hmmm, i cannot reproduce it.  but then i'm using linux, not windows.
@kovrik, what version of racket are you using?  how did you install
geiser, from MELPA? do you have any geiser-specific configuration in
your .emacs?

**Comment by kovrik** [comment]
**OS**: Windows  (at home on OSX it seems to work fine)
**Racket**: v6.2.1
**Geiser**: 20151013.1153 
(geiser-version returns @PACKAGE_STRING@)
Installed from MELPA.

The only geiser-specific line in my config is:
``` scheme
(use-package geiser :defer t)
```
Will try to dig deeper when at work.

**Comment by kovrik** [comment]
With
``` 
(setq geiser-repl-skip-version-check-p t)
```
I'm able to run Racket REPL and everything works perfect..

But still, something is wrong with 
``` scheme
(geiser-repl--version 'racket "Racket.exe")
```

**Comment by kovrik** [comment]
@jaor 
Fixed the problem.

It was caused by single-quotes in geiser-racket.el's (shell-command-to-string (format "%s  -e '(display (version))'" binary)))

Fix (should work in all OSs):
``` patch
diff --git a/geiser-racket.el b/geiser-racket.el_fixed
index ccebcf8..1ce8c78 100644
--- a/geiser-racket.el
+++ b/geiser-racket.el_fixed
@@ -366 +366 @@
-  (shell-command-to-string (format "%s  -e '(display (version))'" binary)))
+  (shell-command-to-string (format "%s  -e %s" binary (shell-quote-argument "(display (version))"))))
```

**Comment by kovrik** [comment]
Also,

I think all `shell-command-to-string` invocations should be changed to use `shell-quote-argument`:
```
grep 'shell-command-to-string' ./*.el
./geiser-chicken.el:  (shell-command-to-string (format "%s -e \"(display (chicken-version))\""
./geiser-guile.el:  (shell-command-to-string (format "%s  -c '(display (version))'" binary)))
./geiser-racket.el:  (shell-command-to-string (format "%s  -e '(display (version))'" binary)))
```

**Comment by kovrik** [comment]
Created a pull request to fix this issue.
