### ISSUE TITLE
Wishlist: Cask + travis.ci + coveralls.io

### ISSUE THREAD

**Issue by dleslie** [jaor/geiser#96]
As detailed by Sacha Chua:
http://sachachua.com/blog/2015/02/continuous-integration-code-coverage-emacs-packages-travis-coveralls/

This would be rather nice for Geiser; but running tests for every supported Scheme would take some work.

**Comment by jaor** [comment]
we are moving the project to gitlab. so please, follow-up there as needed. sorry for the inconvenience!
http://gitlab.com/jaor/geiser/issues/96
